### ISSUE TITLE
ValidationService fails with NPE on Bundles without fullUrl

### ISSUE THREAD

**Issue by alexanderkiel** [HL7/fhir-ig-publisher#103]
I had a publisher run with the following Error:

```
Validating Resources                                                             (00:34.0929)
Terminology server: Check for supported code systems for http://loinc.org        (00:34.0941)
Unhandled Exception: java.lang.NullPointerException                              (00:37.0141)
Publishing Content Failed: null                                                  (00:37.0144)
                                                                                 (00:37.0148)
Use -? to get command line help                                                  (00:37.0153)
                                                                                 (00:37.0156)
Stack Dump (for debugging):                                                      (00:37.0160)
java.lang.NullPointerException
	at org.hl7.fhir.igtools.publisher.ValidationServices.fetch(ValidationServices.java:145)
	at org.hl7.fhir.validation.instance.InstanceValidator.checkReference(InstanceValidator.java:2256)
	at org.hl7.fhir.validation.instance.InstanceValidator.checkChild(InstanceValidator.java:3783)
	at org.hl7.fhir.validation.instance.InstanceValidator.validateElement(InstanceValidator.java:3635)
	at org.hl7.fhir.validation.instance.InstanceValidator.checkExtension(InstanceValidator.java:1448)
	at org.hl7.fhir.validation.instance.InstanceValidator.checkChild(InstanceValidator.java:3792)
	at org.hl7.fhir.validation.instance.InstanceValidator.validateElement(InstanceValidator.java:3635)
	at org.hl7.fhir.validation.instance.InstanceValidator.startInner(InstanceValidator.java:3400)
	at org.hl7.fhir.validation.instance.InstanceValidator.start(InstanceValidator.java:3312)
	at org.hl7.fhir.validation.instance.InstanceValidator.validateResource(InstanceValidator.java:4354)
	at org.hl7.fhir.validation.instance.InstanceValidator.validateContains(InstanceValidator.java:3542)
	at org.hl7.fhir.validation.instance.InstanceValidator.checkChild(InstanceValidator.java:3797)
	at org.hl7.fhir.validation.instance.InstanceValidator.validateElement(InstanceValidator.java:3635)
	at org.hl7.fhir.validation.instance.InstanceValidator.checkChild(InstanceValidator.java:3814)
	at org.hl7.fhir.validation.instance.InstanceValidator.validateElement(InstanceValidator.java:3635)
	at org.hl7.fhir.validation.instance.InstanceValidator.startInner(InstanceValidator.java:3400)
	at org.hl7.fhir.validation.instance.InstanceValidator.start(InstanceValidator.java:3312)
	at org.hl7.fhir.validation.instance.InstanceValidator.validateResource(InstanceValidator.java:4354)
	at org.hl7.fhir.validation.instance.InstanceValidator.validate(InstanceValidator.java:666)
	at org.hl7.fhir.validation.instance.InstanceValidator.validate(InstanceValidator.java:642)
	at org.hl7.fhir.igtools.publisher.Publisher.validate(Publisher.java:4570)
	at org.hl7.fhir.igtools.publisher.Publisher.validate(Publisher.java:4441)
	at org.hl7.fhir.igtools.publisher.Publisher.createIg(Publisher.java:839)
	at org.hl7.fhir.igtools.publisher.Publisher.execute(Publisher.java:696)
	at org.hl7.fhir.igtools.publisher.Publisher.main(Publisher.java:7383)
```

The code looks like this:

```
if (Utilities.isAbsoluteUrl(url)) {
      for (FetchedFile f : files) {
        for (FetchedResource r : f.getResources()) {
          if (r.getElement().fhirType().equals("Bundle")) {
            for (Element be : r.getElement().getChildren("entry")) {
              Element ber = be.getNamedChild("resource");
              if (ber != null) {
                if (be.getChildValue("fullUrl").equals(url))
                  return ber;
              }
            }
          }
        }
      }
    }
```

As we can't assume that a `fullUrl` is present, we just should check for `null` here and obviously don't match. I can file a PR, but on the other hand this change is tiny.

The resource causing this NPE was in the IG under `input/resources`.

**Comment by lmckenzi** [comment]
Is this issue still happening @alexanderkiel ?

**Comment by alexanderkiel** [comment]
@lmckenzi It's not relevant anymore for me, so I'll close this issue.
