### ISSUE TITLE
Building an IG with no resources raises FHIRException

### ISSUE THREAD

**Issue by barabo** [HL7/fhir-ig-publisher#125]
I'm building an IG that consists entirely of markdown (no resources, no examples, nada) and getting the following exception from the `SimpleFetcher.scan` function:

```bash
can@msft-mbp ~/code/ig/docs () $ bash _genonce.sh
Checking internet connection...
Online

FHIR IG Publisher Version 1.1.1 (Git# d3432fbc0971). Built 2020-07-04T00:36:51.739Z (71 hours old)
File log: /var/folders/7j/qrfr1sds12d9bv2dsb450wrm0000gn/T/fhir-ig-publisher-tmp.log
Detected Java version: 12.0.2 from /Library/Java/JavaVirtualMachines/adoptopenjdk-12.0.2.jdk/Contents/Home on x86_64 (64bit). 4096MB available
Parameters: -ig ig.ini

dir = /Users/can/code/ig/docs, path = /Users/can/.gem/ruby/2.7.0/bin:/usr/local/opt/ruby/bin:/Users/can/.nvm/versions/node/v11.0.0/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/share/dotnet:~/.dotnet/tools:/Users/can/Library/Python/3.7/bin:/Users/can/go/bin

Run time = Monday, July 6, 2020 at 6:53:57 PM Central Daylight Time (2020-07-06T18:53:57-05:00)
Package Cache: /Users/can/.fhir/packages                                         (00:00.0031)
Load Template from hl7.fhir.template                                             (00:00.0712)
Installing hl7.fhir.template#current to the package cache
  Fetching:
  Installing:  done.
 Load Template from hl7.base.template#current                                    (00:02.0340)
Installing hl7.base.template#current to the package cache
  Fetching:
  Installing:  done.
  Load Template from fhir.base.template#current                                  (00:02.0459)
Installing fhir.base.template#current to the package cache
  Fetching:.
  Installing: . done.

onLoad.findSpreadsheets:

onLoad.updateIg:
     [xslt] Processing /Users/can/code/ig/docs/template/onLoad-ig-working.xml to /Users/can/code/ig/docs/template/onLoad-ig-updated.xml
     [xslt] Loading stylesheet /Users/can/code/ig/docs/template/scripts/onLoad.xslt

onLoad.extend:

onLoad:
Root directory: /Users/can/code/ig/docs                                       (00:09.0112)
Core Package hl7.fhir.r4.core#4.0.1
Terminology Cache is at /Users/can/code/ig/docs/input-cache/txcache. 0 files in cache (00:14.0716)
Connect to Terminology Server at http://tx.fhir.org                              (00:14.0719)
Load Package hl7.fhir.pubpack#0.0.6
Load Package hl7.fhir.xver-extensions#0.0.4
Initialization complete                                                          (00:15.0876)
Load Content                                                                     (00:15.0876)
Publishing Content Failed: No Source directories to scan found                   (00:15.0925)
                                                                                 (00:15.0925)
Use -? to get command line help                                                  (00:15.0926)
                                                                                 (00:15.0926)
Stack Dump (for debugging):                                                      (00:15.0926)
org.hl7.fhir.exceptions.FHIRException: No Source directories to scan found
	at org.hl7.fhir.igtools.publisher.SimpleFetcher.scan(SimpleFetcher.java:260)
	at org.hl7.fhir.igtools.publisher.Publisher.loadResources(Publisher.java:3441)
	at org.hl7.fhir.igtools.publisher.Publisher.load(Publisher.java:2954)
	at org.hl7.fhir.igtools.publisher.Publisher.createIg(Publisher.java:842)
	at org.hl7.fhir.igtools.publisher.Publisher.execute(Publisher.java:708)
	at org.hl7.fhir.igtools.publisher.Publisher.main(Publisher.java:7809)
```

Looking at the [code](https://github.com/HL7/fhir-ig-publisher/blob/e2fe0e4afcf5986a2c5727d8c66c576d51676dfa/org.hl7.fhir.publisher.core/src/main/java/org/hl7/fhir/igtools/publisher/SimpleFetcher.java#L260) I see this:

```java
  @Override
  public List<FetchedFile> scan(String sourceDir, IWorkerContext context, boolean autoPath) throws IOException, FHIRException {
    List<String> sources = new ArrayList<String>();
    if (sourceDir != null)
      sources.add(sourceDir);
    if (autoPath)
      sources.addAll(resourceDirs);
    if (sources.isEmpty())
      throw new FHIRException("No Source directories to scan found"); // though it's not possible to get to this point...
```

I've recreated this using the sushi-provided `minimal-config.yaml` and a minimal `index.md` file.  If you have a bash shell, you should be able to paste the code below and play along (I haven't tried in windows, but it should work in a bash shell).

```bash
mkdir -p ~/code/ig/fsh/ig-data/input/pagecontent
cd $_
echo -e "# Hello\nWorld" > index.md
cd ../../..
curl https://build.fhir.org/ig/HL7/fhir-shorthand/minimal-config.yaml > config.yaml
sed -i -e '/^template/s:#.*::' config.yaml # HACK to remove the #0.0.5 template version from the file
cd ..
sushi fsh -o docs
cd docs
wget https://raw.githubusercontent.com/FHIR/sample-ig/master/_updatePublisher.sh
bash _updatePublisher.sh -f
wget https://raw.githubusercontent.com/FHIR/sample-ig/master/_genonce.sh
bash _genonce.sh
# See the stack trace above.
```

For now, I've been able to build the IG by creating an `fsh/ig-data/input/examples/patient-example.json` example which I borrowed from the Patient examples.  And I also had to remove the `template` from the minimal `config.yaml`, replacing it with a simple `menu` in `ig.ini`.  I couldn't find an easier way to convince the publisher to keep going.  The steps are shown below.

### The Point
I'm not sure what to really ask for with this issue, though.  I suppose it's possible that if the code had not raised an exception it may have crashed later anyway.  **However, if an 'all markdown' IG is to be supported, I think the publisher should handle this gracefully.**

Anyway, this is what I've done to satisfy the publisher with the toy example.

```bash
cd ~/code/ig
sed -i -e '/^id: fhir/s: fhir: hl7.fhir:' fsh/config.yaml  # HACK: insert an HL7 before fhir.
sed -i -e '/^template:/s:^:#:' fsh/config.yaml  # HACK: disable the template entirely.

cat <<EOF>> fsh/config.yaml
menu:
  IG Home: index.html
  TOC: toc.html
EOF

cat <<EOF> fsh/ig-data/ig.ini
[IG]
ig = input/ImplementationGuide-hl7.fhir.us.minimal.json
template = fhir.base.template
EOF

mkdir fsh/ig-data/input/examples
cd $_
wget https://www.hl7.org/fhir/patient-example.json
cd ~/code/ig
sushi fsh -o docs
cd docs
bash _genonce.sh  # bringo, check it out
```

**Comment by grahamegrieve** [comment]
I don't entirely understand. The code you've quoted says that you have to configure the IG with a source directory, not that it has to contain a resource. It seems appropriate to me to require that a source directory be configured; that's nothing to do with requiring a resource.

**Comment by barabo** [comment]
Thank you, Graham!  I was not looking carefully enough at what caused the exception.

Incidentally, I found that by adding a `mkdir -p docs/input/examples` after my sushi step but before running `_genonce.sh` - I could get the publisher to run!

Unfortunately, I was unable to get sushi to create the empty `examples` directory for me.  Since my IG depends on sushi output feeding the publisher, I need sushi to produce an `input` folder that the publisher can process.

So, it seems that two options would work for me.  Either I get sushi to add a feature where it allows an empty `examples` directory to be created - or the publisher changes to *not* raise an exception when there are no sources to iterate over.

**Comment by grahamegrieve** [comment]
Sounds like you should raise it here for discussion: https://chat.fhir.org/#narrow/stream/215610-shorthand

**Comment by lmckenzi** [comment]
This doesn't seem to be a publisher issue, so closing.
