### ISSUE TITLE
ExampleScenario rendering is not working

### ISSUE THREAD

**Issue by costateixeira** [HL7/fhir-ig-publisher#136]
When trying to add an exampleScenario, this shows up:
Exception in thread "main" java.lang.Error: The resource type "ExampleScenario" does not implement the property "description"
        at org.hl7.fhir.r5.model.ExampleScenario.getDescriptionElement(ExampleScenario.java:4604)
        at org.hl7.fhir.igtools.publisher.Publisher.getDesc(Publisher.java:6289)
        at org.hl7.fhir.igtools.publisher.Publisher.genEntryItem(Publisher.java:6180)
        at org.hl7.fhir.igtools.publisher.Publisher.genResourceReferencesList(Publisher.java:6270)
        at org.hl7.fhir.igtools.publisher.Publisher.generateResourceReferences(Publisher.java:6226)
        at org.hl7.fhir.igtools.publisher.Publisher.generateResourceReferences(Publisher.java:6040)
        at org.hl7.fhir.igtools.publisher.Publisher.generateSummaryOutputs(Publisher.java:5412)
        at org.hl7.fhir.igtools.publisher.Publisher.generate(Publisher.java:4708)
        at org.hl7.fhir.igtools.publisher.Publisher.createIg(Publisher.java:859)
        at org.hl7.fhir.igtools.publisher.Publisher.execute(Publisher.java:708)
        at org.hl7.fhir.igtools.publisher.Publisher.main(Publisher.java:7835)

**Comment by costateixeira** [comment]
Seems the issue is here
https://github.com/HL7/fhir-ig-publisher/blob/master/org.hl7.fhir.publisher.core/src/main/java/org/hl7/fhir/igtools/publisher/Publisher.java#L6355

between 1.1.2 and 1.1.3, there was a change that removed the check to see if the resource has a description.
https://github.com/HL7/fhir-ig-publisher/compare/1.1.2...1.1.3#diff-8ba944eececf281bdf40b620083d2e9eL6266

(I cannot create a PR because I do not know what should the result be if the resource has no description.)

**Comment by costateixeira** [comment]
This has been fixed meanwhile.
