### ISSUE TITLE
external link to google forms crashes igpublisher

### ISSUE THREAD

**Issue by oliveregger** [HL7/fhir-ig-publisher#230]
For our template we added the feature that a google form can be added for feedback:
https://github.com/hl7ch/ig-template

adding this link however is not in favor of the igpublisher, he stalls for a few minutes and then crashes:
https://docs.google.com/forms/d/e/1FAIpQLSeZjRSISsMmPJawlA6EbFNg1kQyu013AilssLb5AohZ2vUCDw/viewform?usp=sf_link&entry.1353807103=ch.fhir.ig.ch-core%231.1.0%20%2FBundle-1-ZuweisungZurRadiologischenDiagnostik-FHIR.html&entry.247644557=1-ZuweisungZurRadiologischenDiagnostik-FHIR

Exception in thread "main" java.lang.OutOfMemoryError: Requested array size exceeds VM limit
        at java.base/java.util.Arrays.copyOf(Arrays.java:3536)
        at java.base/java.lang.AbstractStringBuilder.ensureCapacityInternal(AbstractStringBuilder.java:227)
        at java.base/java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:808)
        at java.base/java.lang.StringBuilder.append(StringBuilder.java:240)
        at org.hl7.fhir.utilities.xhtml.XhtmlParser.readUntil(XhtmlParser.java:869)
        at org.hl7.fhir.utilities.xhtml.XhtmlParser.parseLiteral(XhtmlParser.java:877)
        at org.hl7.fhir.utilities.xhtml.XhtmlParser.parseAttributeValue(XhtmlParser.java:648)
        at org.hl7.fhir.utilities.xhtml.XhtmlParser.parseAttributes(XhtmlParser.java:632)
        at org.hl7.fhir.utilities.xhtml.XhtmlParser.parseElement(XhtmlParser.java:594)
        at org.hl7.fhir.utilities.xhtml.XhtmlParser.parseElementInner(XhtmlParser.java:570)
        at org.hl7.fhir.utilities.xhtml.XhtmlParser.parseElement(XhtmlParser.java:602)
        at org.hl7.fhir.utilities.xhtml.XhtmlParser.parseElementInner(XhtmlParser.java:570)
        at org.hl7.fhir.utilities.xhtml.XhtmlParser.parseElement(XhtmlParser.java:602)
        at org.hl7.fhir.utilities.xhtml.XhtmlParser.parseElementInner(XhtmlParser.java:570)
        at org.hl7.fhir.utilities.xhtml.XhtmlParser.parseElement(XhtmlParser.java:602)
        at org.hl7.fhir.utilities.xhtml.XhtmlParser.parseElementInner(XhtmlParser.java:570)
        at org.hl7.fhir.utilities.xhtml.XhtmlParser.parseElement(XhtmlParser.java:602)
        at org.hl7.fhir.utilities.xhtml.XhtmlParser.parseElementInner(XhtmlParser.java:570)
        at org.hl7.fhir.utilities.xhtml.XhtmlParser.parseElement(XhtmlParser.java:602)
        at org.hl7.fhir.utilities.xhtml.XhtmlParser.parseElementInner(XhtmlParser.java:570)
        at org.hl7.fhir.utilities.xhtml.XhtmlParser.parseElement(XhtmlParser.java:602)
        at org.hl7.fhir.utilities.xhtml.XhtmlParser.parseElementInner(XhtmlParser.java:570)
        at org.hl7.fhir.utilities.xhtml.XhtmlParser.parse(XhtmlParser.java:464)
        at org.hl7.fhir.utilities.xhtml.XhtmlParser.parse(XhtmlParser.java:438)
        at org.hl7.fhir.igtools.publisher.HTLMLInspector.loadFile(HTLMLInspector.java:352)
        at org.hl7.fhir.igtools.publisher.HTLMLInspector.check(HTLMLInspector.java:228)
        at org.hl7.fhir.igtools.publisher.Publisher.generate(Publisher.java:5010)
        at org.hl7.fhir.igtools.publisher.Publisher.createIg(Publisher.java:888)
        at org.hl7.fhir.igtools.publisher.Publisher.execute(Publisher.java:732)
        at org.hl7.fhir.igtools.publisher.Publisher.main(Publisher.java:8417)

**Comment by oliveregger** [comment]
The issue is, that the url was not correctly escaped:

https://docs.google.com/forms/d/e/1FAIpQLSeZjRSISsMmPJawlA6EbFNg1kQyu013AilssLb5AohZ2vUCDw/viewform?usp=sf_link&entry.1353807103=ch.fhir.ig.ch-core%231.1.0%20%2FBundle-1-ZuweisungZurRadiologischenDiagnostik-FHIR.html&entry.247644557=1-ZuweisungZurRadiologischenDiagnostik-FHIR

1. & needs to be &amp;   sf_link&entry -> sf_link&amp;entry. 

(and entry. -> entry%2E etc, but the uri_escape etc, but that was not causing the stalling)

**Comment by costateixeira** [comment]
@oliveregger do you want to close this issue?

**Comment by oliveregger** [comment]
i will provide a fix, i think the igpublisher should generate an error instead of a crash

**Comment by grahamegrieve** [comment]
fixed
