### ISSUE TITLE
FHIR IG Publisher Version 1.1.79 Exception generating resource error for value set

### ISSUE THREAD

**Issue by dmangum2** [HL7/fhir-ig-publisher#310]
FHIR IG Publisher Version 1.1.79 error and didn't get in 1.1.77

Exception generating resource C:....\build\input\vocabulary\valueset-appointment-cancellation-reason::ValueSet/appointment-cancellation-reason: The workbook already contains a sheet named 'Include from Appointment Cancellation Reason Codes' (02:56.0085)
java.lang.IllegalArgumentException: The workbook already contains a sheet named 'Include from Appointment Cancellation 
Reason Codes'
        at org.apache.poi.xssf.usermodel.XSSFWorkbook.validateSheetName(XSSFWorkbook.java:910)
        at org.apache.poi.xssf.usermodel.XSSFWorkbook.createSheet(XSSFWorkbook.java:863)
        at org.hl7.fhir.r5.renderers.spreadsheets.ValueSetSpreadsheetGenerator.genIncludeSystem(ValueSetSpreadsheetGenerator.java:117)
        at org.hl7.fhir.r5.renderers.spreadsheets.ValueSetSpreadsheetGenerator.genInclude(ValueSetSpreadsheetGenerator.java:87)
        at org.hl7.fhir.r5.renderers.spreadsheets.ValueSetSpreadsheetGenerator.renderValueSet(ValueSetSpreadsheetGenerator.java:40)
        at org.hl7.fhir.igtools.publisher.Publisher.generateOutputsValueSet(Publisher.java:7815)
        at org.hl7.fhir.igtools.publisher.Publisher.generateResourceHtml(Publisher.java:6882)
        at org.hl7.fhir.igtools.publisher.Publisher.generateHtmlOutputs(Publisher.java:6840)
        at org.hl7.fhir.igtools.publisher.Publisher.generate(Publisher.java:5052)
        at org.hl7.fhir.igtools.publisher.Publisher.createIg(Publisher.java:908)
        at org.hl7.fhir.igtools.publisher.Publisher.execute(Publisher.java:752)
        at org.hl7.fhir.igtools.publisher.Publisher.main(Publisher.java:8664)
   org.apache.poi.xssf.usermodel.XSSFWorkbook.validateSheetName(XSSFWorkbook.java:910) (02:56.0130)
   org.apache.poi.xssf.usermodel.XSSFWorkbook.createSheet(XSSFWorkbook.java:863) (02:56.0134)
   org.hl7.fhir.r5.renderers.spreadsheets.ValueSetSpreadsheetGenerator.genIncludeSystem(ValueSetSpreadsheetGenerator.java:117) (02:56.0138)
   org.hl7.fhir.r5.renderers.spreadsheets.ValueSetSpreadsheetGenerator.genInclude(ValueSetSpreadsheetGenerator.java:87) (02:56.0141)
   org.hl7.fhir.r5.renderers.spreadsheets.ValueSetSpreadsheetGenerator.renderValueSet(ValueSetSpreadsheetGenerator.java:40) (02:56.0145)
   org.hl7.fhir.igtools.publisher.Publisher.generateOutputsValueSet(Publisher.java:7815) (02:56.0149)
   org.hl7.fhir.igtools.publisher.Publisher.generateResourceHtml(Publisher.java:6882) (02:56.0152)
   org.hl7.fhir.igtools.publisher.Publisher.generateHtmlOutputs(Publisher.java:6840) (02:56.0154)
   org.hl7.fhir.igtools.publisher.Publisher.generate(Publisher.java:5052)        (02:56.0156)
   org.hl7.fhir.igtools.publisher.Publisher.createIg(Publisher.java:908)         (02:56.0159)
   org.hl7.fhir.igtools.publisher.Publisher.execute(Publisher.java:752)          (02:56.0161)
   org.hl7.fhir.igtools.publisher.Publisher.main(Publisher.java:8664)            (02:56.0165)

AppointmentCancellationReasonCodes.fsh:
CodeSystem:     AppointmentCancellationReasonCodeSystem
Id:             appointment-cancellation-reason
Title:          "Appointment Cancellation Reason Codes"
Description:    "Extended reasons for the cancellation of an appointment"
* #deleted      "Deleted"       "Appointment was either logically deleted or physically deleted"
* #rescheduled  "Rescheduled"   "Appointment was rescheduled"

ValueSet:     AppointmentCancellationReasonValueSet
Id:             appointment-cancellation-reason
Title:          "Appointment Cancellation Reason Value Set"
Description:    "Extended set of reasons for the cancellation of an appointment"
* codes from system http://terminology.hl7.org/CodeSystem/appointment-cancellation-reason
* codes from system AppointmentCancellationReasonCodeSystem

No such message in the QA Report
Using sushi v0.16.0; also tried sushi 2.0.1

**Comment by lmckenzi** [comment]
@dmangum2 - is this issue still a problem?

**Comment by dmangum2** [comment]
Hi - In progress of upgrading sushi. Will confirm in next week or so.

**Comment by lmckenzi** [comment]
@dmangum2 Poking again on whether this is a problem.  If no confirmation, we'll close

**Comment by lmckenzi** [comment]
No further response, so presuming no longer an issue
