### ISSUE TITLE
Error loading template fhir.base.template: null - publisher 1.1.79

### ISSUE THREAD

**Issue by janesp** [HL7/fhir-ig-publisher#312]
As a publisher first-timer, I am following https://youtu.be/gQjhISe9q_A guidance/instructions for a minimal technical IG setup (macOS Big Sur, publisher 1.1.79, also tried 1.1.80 Snapshot), getting `Publishing Content Failed: Error loading template fhir.base.template: null`

Full CLI output:

```
peterjanes@Blackbird ig_root % java -jar publisher_1.1.79.jar -ig ig.ini
FHIR IG Publisher Version 1.1.79 (Git# 863af8ce3c97). Built 2021-09-02T17:05:28.25Z (5 days old)
Detected Java version: 1.8.0_301 from /Library/Internet Plug-Ins/JavaAppletPlugin.plugin/Contents/Home on Mac OS X/x86_64 (64bit). 14564MB available
dir = /Users/peterjanes/Dev/FHIR/fhir-ig-test/ig_root, path = /Users/peterjanes/.nvm/versions/node/v16.8.0/bin:/Users/peterjanes/.rbenv/shims:/Users/peterjanes/.gem/ruby/3.0.0/bin:/usr/local/opt/ruby/bin:/usr/local/lib/ruby/gems/3.0.0/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Applications/VMware Fusion.app/Contents/Public:/usr/local/share/dotnet:/opt/X11/bin:~/.dotnet/tools:/Library/Apple/usr/bin:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/Users/peterjanes/drush
Parameters: -ig ig.ini
Start Clock @ Tuesday, September 7, 2021 8:05:27 PM CEST (2021-09-07T20:05:27+02:00)

API keys loaded from /Users/peterjanes/fhir-api-keys.ini                         (00:00.0018)
Package Cache: /Users/peterjanes/.fhir/packages                                  (00:00.0020)
Load Template from fhir.base.template                                            (00:00.0532)
2021-09-07 20:05:29.063 [main] INFO  o.h.f.u.npm.BasePackageCacheManager [BasePackageCacheManager.java:80] Failed to resolve package fhir.base.template#null from server: http://packages.fhir.org
2021-09-07 20:05:29.908 [main] INFO  o.h.f.u.npm.BasePackageCacheManager [BasePackageCacheManager.java:80] Failed to resolve package fhir.base.template#null from server: https://packages2.fhir.org/packages
2021-09-07 20:05:30.041 [main] INFO  o.h.f.u.npm.BasePackageCacheManager [BasePackageCacheManager.java:80] Failed to resolve package fhir.base.template#null.x from server: http://packages.fhir.org
2021-09-07 20:05:30.298 [main] INFO  o.h.f.u.npm.BasePackageCacheManager [BasePackageCacheManager.java:80] Failed to resolve package fhir.base.template#null.x from server: https://packages2.fhir.org/packages
Publishing Content Failed: Error loading template fhir.base.template: null       (00:04.0479)
                                                                                 (00:04.0480)
Use -? to get command line help                                                  (00:04.0480)
                                                                                 (00:04.0481)
Stack Dump (for debugging):                                                      (00:04.0482)
org.hl7.fhir.exceptions.FHIRException: Error loading template fhir.base.template: null
	at org.hl7.fhir.igtools.templates.TemplateManager.loadPackage(TemplateManager.java:277)
	at org.hl7.fhir.igtools.templates.TemplateManager.installTemplate(TemplateManager.java:93)
	at org.hl7.fhir.igtools.templates.TemplateManager.loadTemplate(TemplateManager.java:79)
	at org.hl7.fhir.igtools.publisher.Publisher.initializeFromIg(Publisher.java:1672)
	at org.hl7.fhir.igtools.publisher.Publisher.initialize(Publisher.java:1487)
	at org.hl7.fhir.igtools.publisher.Publisher.execute(Publisher.java:746)
	at org.hl7.fhir.igtools.publisher.Publisher.main(Publisher.java:8664)
Caused by: java.lang.NullPointerException
	at org.hl7.fhir.utilities.npm.FilesystemPackageCacheManager.fetchTheOldWay(FilesystemPackageCacheManager.java:717)
	at org.hl7.fhir.utilities.npm.FilesystemPackageCacheManager.loadFromPackageServer(FilesystemPackageCacheManager.java:226)
	at org.hl7.fhir.utilities.npm.FilesystemPackageCacheManager.loadPackage(FilesystemPackageCacheManager.java:500)
	at org.hl7.fhir.igtools.templates.TemplateManager.loadPackage(TemplateManager.java:247)
	... 6 more
```
Content of `ig.ini`:

```
[IG]
ig = input/ig.json
template = fhir.base.template
```

Any hints would be much appreciated!

**Comment by grahamegrieve** [comment]
the only supported version at this time is 1.1.79

**Comment by janesp** [comment]
> the only supported version at this time is 1.1.79

Many thanks for the quick response!

It appears to me that my publisher version actually **is** 1.1.79 (reading this from its first output line), although the download button of the current version says 1.1.51 - I have updated the output accordingly (using a renamed jar file).

Any idea what could be wrong?

**Comment by grahamegrieve** [comment]
looks like that NPE will happen if you run it without network access

**Comment by janesp** [comment]
> looks like that NPE will happen if you run it without network access

The notebook has network access - I just checked JVM network settings, trying both browser settings (default) and direct connection - no success, unfortunately; running out of ideas...

**Comment by grahamegrieve** [comment]
well, next version won't suppress the actual error and it will become available so there'll be more information.

**Comment by janesp** [comment]
> well, next version won't suppress the actual error and it will become available so there'll be more information.

Many thanks, looking forward!

I am just wondering if I am the first one to run into this issue (or if the bug just bites me as a newbie 😉)

**Comment by janesp** [comment]
I found the solution (thanks to a good FSH template 😊) - `ig.ini` needs to be amended:

- `template = fhir.base.template` doesn't work (my example was obviously outdated)
- `template = fhir.base.template#current` works fine

**Comment by lmckenzi** [comment]
Seems to be addressed.  Closing
