### ISSUE TITLE
HTML Render Bug if List.encounter is populated

### ISSUE THREAD

**Issue by patrick-werner** [HL7/fhir-ig-publisher#315]
Project to show the issue: https://github.com/patrick-werner/listEncounterFHIRbug

```
Exception in thread "main" java.lang.Error: Wrong node type
	at org.hl7.fhir.utilities.xhtml.XhtmlNode.addText(XhtmlNode.java:270)
	at org.hl7.fhir.utilities.xhtml.XhtmlNode.tx(XhtmlNode.java:638)
	at org.hl7.fhir.r5.renderers.ListRenderer.shortForRef(ListRenderer.java:222)
	at org.hl7.fhir.r5.renderers.ListRenderer.render(ListRenderer.java:62)
	at org.hl7.fhir.r5.renderers.ResourceRenderer.render(ResourceRenderer.java:84)
	at org.hl7.fhir.igtools.publisher.Publisher.generateNarratives(Publisher.java:1180)
	at org.hl7.fhir.igtools.publisher.Publisher.loadConformance(Publisher.java:3921)
	at org.hl7.fhir.igtools.publisher.Publisher.createIg(Publisher.java:897)
	at org.hl7.fhir.igtools.publisher.Publisher.execute(Publisher.java:752)
	at org.hl7.fhir.igtools.publisher.Publisher.main(Publisher.java:8664)
```

**Comment by patrick-werner** [comment]
Zulip Thread: https://chat.fhir.org/#narrow/stream/179252-IG-creation/topic/IG.20Publisher.3A.20Bug.20if.20List.20Instance.20contains.20.20encounter

**Comment by lmckenzi** [comment]
@patrick-werner, is this still a problem?
