### ISSUE TITLE
Use terminology server flag not working

### ISSUE THREAD

**Issue by rgeimer** [HL7/fhir-ig-publisher#324]
If the terminology server is down, it used to be possible to set the use terminology server flag to false and continue building. That is no longer the case. If the terminology server is down and you set that flag, you still get the following error:

Publishing Content Failed: Attempt to use Terminology server when no Terminology server is available (00:19.0628)
(00:19.0628)
Use -? to get command line help                                                  (00:19.0628)
(00:19.0629)
Stack Dump (for debugging):                                                      (00:19.0629)
org.hl7.fhir.exceptions.FHIRException: Attempt to use Terminology server when no Terminology server is available
at org.hl7.fhir.r5.context.BaseWorkerContext.validateCodeBatch(BaseWorkerContext.java:824)
at org.hl7.fhir.r5.renderers.ValueSetRenderer.getConceptsForCodes(ValueSetRenderer.java:1009)
	at org.hl7.fhir.r5.renderers.ValueSetRenderer.genInclude(ValueSetRenderer.java:825)
at org.hl7.fhir.r5.renderers.ValueSetRenderer.generateComposition(ValueSetRenderer.java:754)
	at org.hl7.fhir.r5.renderers.ValueSetRenderer.render(ValueSetRenderer.java:84)
at org.hl7.fhir.r5.renderers.ValueSetRenderer.render(ValueSetRenderer.java:73)
	at org.hl7.fhir.r5.renderers.ResourceRenderer.render(ResourceRenderer.java:74)
at org.hl7.fhir.igtools.publisher.Publisher.generateNarratives(Publisher.java:1183)
	at org.hl7.fhir.igtools.publisher.Publisher.loadConformance(Publisher.java:3974)
at org.hl7.fhir.igtools.publisher.Publisher.createIg(Publisher.java:907)
	at org.hl7.fhir.igtools.publisher.Publisher.execute(Publisher.java:759)
	at org.hl7.fhir.igtools.publisher.Publisher.main(Publisher.java:8762)

**Comment by lmckenzi** [comment]
We agree that it should be possible to run the publisher without a terminology server (i.e. with the n/a value).  We will fix the crash and also ensure that there's a big bold QA warning that the publisher was run without a terminology server.  Also, some content may not render 'nicely'.  Will adjust the verbiage in the documentation to reflect this capability (and its limitations).

**Comment by lmckenzi** [comment]
@rgeimer can you confirm if this is now fixed?
