### ISSUE TITLE
Publisher crashes looking for non-existent element

### ISSUE THREAD

**Issue by markkramerus** [HL7/fhir-ig-publisher#329]
Version 1.1.83 has trouble with validating my bundle. 

I'm not sure why it would be looking for Bundle.entry.resource.referenceRange.

Here's the error message:
```
onGenerate.jira:

onGenerate.extend:

onGenerate:
Exception in thread "main" java.lang.Error: getElementByName: can't find #Bundle.entry.resource.referenceRange in [Bundle, Bundle.id, Bundle.meta, Bundle.implicitRules, Bundle.language, Bundle.identifier, Bundle.type, Bundle.timestamp, Bundle.total, Bundle.link, Bundle.link.id, Bundle.link.extension, Bundle.link.modifierExtension, Bundle.link.relation, Bundle.link.url, Bundle.entry, Bundle.entry.id, Bundle.entry.extension, Bundle.entry.modifierExtension, Bundle.entry.link, Bundle.entry.fullUrl, Bundle.entry.resource, Bundle.entry.search, Bundle.entry.search.id, Bundle.entry.search.extension, Bundle.entry.search.modifierExtension, Bundle.entry.search.mode, Bundle.entry.search.score, Bundle.entry.request, Bundle.entry.request.id, Bundle.entry.request.extension, Bundle.entry.request.modifierExtension, Bundle.entry.request.method, Bundle.entry.request.url, Bundle.entry.request.ifNoneMatch, Bundle.entry.request.ifModifiedSince, Bundle.entry.request.ifMatch, Bundle.entry.request.ifNoneExist, Bundle.entry.response, Bundle.entry.response.id, Bundle.entry.response.extension, Bundle.entry.response.modifierExtension, Bundle.entry.response.status, Bundle.entry.response.location, Bundle.entry.response.etag, Bundle.entry.response.lastModified, Bundle.entry.response.outcome, Bundle.signature] from http://hl7.org/fhir/StructureDefinition/Bundle
        at org.hl7.fhir.r5.conformance.ProfileUtilities.getElementByName(ProfileUtilities.java:3679)
        at org.hl7.fhir.r5.conformance.ProfileUtilities.genTypes(ProfileUtilities.java:3435)
        at org.hl7.fhir.r5.conformance.ProfileUtilities.genElementCells(ProfileUtilities.java:4185)
        at org.hl7.fhir.r5.conformance.ProfileUtilities.genElement(ProfileUtilities.java:4005)
        at org.hl7.fhir.r5.conformance.ProfileUtilities.genElement(ProfileUtilities.java:4071)
        at org.hl7.fhir.r5.conformance.ProfileUtilities.genElement(ProfileUtilities.java:4071)
        at org.hl7.fhir.r5.conformance.ProfileUtilities.genElement(ProfileUtilities.java:4071)
        at org.hl7.fhir.r5.conformance.ProfileUtilities.genElement(ProfileUtilities.java:4071)
        at org.hl7.fhir.r5.conformance.ProfileUtilities.generateTable(ProfileUtilities.java:3839)
        at org.hl7.fhir.igtools.renderers.StructureDefinitionRenderer.snapshot(StructureDefinitionRenderer.java:353)
        at org.hl7.fhir.igtools.publisher.Publisher.generateOutputsStructureDefinition(Publisher.java:7994)
        at org.hl7.fhir.igtools.publisher.Publisher.generateResourceHtml(Publisher.java:6976)
        at org.hl7.fhir.igtools.publisher.Publisher.generateHtmlOutputs(Publisher.java:6920)
        at org.hl7.fhir.igtools.publisher.Publisher.generate(Publisher.java:5120)
        at org.hl7.fhir.igtools.publisher.Publisher.createIg(Publisher.java:914)
        at org.hl7.fhir.igtools.publisher.Publisher.execute(Publisher.java:753)
        at org.hl7.fhir.igtools.publisher.Publisher.main(Publisher.java:8766)
Press any key to continue . . .
```

**Comment by lmckenzi** [comment]
Please verify if this is still an issue and, if so, provide the following information: the specific IG, what version of the publisher you were using and what branch of the IG creates this issue.

**Comment by lmckenzi** [comment]
@markkramerus - can you confirm if this still an issue?

**Comment by lmckenzi** [comment]
No response, so presume no longer an issue.
