### ISSUE TITLE
issue with cda-core-2.0:  java.lang.OutOfMemoryError: Java heap space

### ISSUE THREAD

**Issue by oliveregger** [HL7/fhir-ig-publisher#36]
Load Terminology Cache from /tmp/fhircache                                       (00:22.0317)
Connect to Terminology Server at http://tx.fhir.org                              (00:22.0318)
Load Content                                                                     (00:23.0829)
Processing Conformance Resources                                                 (00:25.0124)
Generating Narratives                                                            (01:13.0317)
Validating Resources                                                             (01:13.0318)
Generating Outputs in /scratch/ig-build-temp-MMO6M4/repo/output                  (01:13.0318)
No value set found at RecordTarget.typeCode (url = 'http://terminology.hl7.org/ValueSet/v3-ParticipationType')
No value set found at RecordTarget.contextControlCode (url = 'http://terminology.hl7.org/ValueSet/v3-ContextControl')
No value set found at RecordTarget.typeCode (url = 'http://terminology.hl7.org/ValueSet/v3-ParticipationType')
No value set found at RecordTarget.contextControlCode (url = 'http://terminology.hl7.org/ValueSet/v3-ContextControl')
No value set found at Material.code (url = 'http://hl7.org/fhir/ValueSet/v3-MaterialEntityClassType')
No value set found at Material.code (url = 'http://hl7.org/fhir/ValueSet/v3-MaterialEntityClassType')
No value set found at Authorization.typeCode (url = 'http://terminology.hl7.org/ValueSet/v3-ParticipationType')
No value set found at Authorization.typeCode (url = 'http://terminology.hl7.org/ValueSet/v3-ParticipationType')
No value set found at Device.manufacturerModelName (url = 'http://hl7.org/fhir/ValueSet/v3-ManufacturerModelName')
No value set found at Device.softwareName (url = 'http://hl7.org/fhir/ValueSet/v3-SoftwareName')
No value set found at Device.manufacturerModelName (url = 'http://hl7.org/fhir/ValueSet/v3-ManufacturerModelName')
No value set found at Device.softwareName (url = 'http://hl7.org/fhir/ValueSet/v3-SoftwareName')
No value set found at LegalAuthenticator.typeCode (url = 'http://terminology.hl7.org/ValueSet/v3-ParticipationType')
No value set found at LegalAuthenticator.contextControlCode (url = 'http://terminology.hl7.org/ValueSet/v3-ContextControl')
No value set found at LegalAuthenticator.typeCode (url = 'http://terminology.hl7.org/ValueSet/v3-ParticipationType')
No value set found at LegalAuthenticator.contextControlCode (url = 'http://terminology.hl7.org/ValueSet/v3-ContextControl')
No value set found at RelatedDocument.typeCode (url = 'http://terminology.hl7.org/ValueSet/v3-ParticipationType')
No value set found at RelatedDocument.typeCode (url = 'http://terminology.hl7.org/ValueSet/v3-ParticipationType')
No value set found at ParentDocument.code (url = 'http://hl7.org/fhir/ValueSet/v3-DocumentType')
No value set found at ParentDocument.code (url = 'http://hl7.org/fhir/ValueSet/v3-DocumentType')
No value set found at Component2.typeCode (url = 'http://terminology.hl7.org/ValueSet/v3-ParticipationType')
No value set found at Component2.typeCode (url = 'http://terminology.hl7.org/ValueSet/v3-ParticipationType')
No value set found at ON.use (url = 'http://hl7.org/fhir/ValueSet/v3-OrganizationNameUse')
No value set found at ON.use (url = 'http://hl7.org/fhir/ValueSet/v3-OrganizationNameUse')
No value set found at Participant.typeCode (url = 'http://terminology.hl7.org/ValueSet/v3-ParticipationType')
No value set found at Participant.contextControlCode (url = 'http://terminology.hl7.org/ValueSet/v3-ContextControl')
No value set found at Participant.typeCode (url = 'http://terminology.hl7.org/ValueSet/v3-ParticipationType')
No value set found at Participant.contextControlCode (url = 'http://terminology.hl7.org/ValueSet/v3-ContextControl')
No value set found at AuthoringDevice.manufacturerModelName (url = 'http://hl7.org/fhir/ValueSet/v3-ManufacturerModelName')
No value set found at AuthoringDevice.softwareName (url = 'http://hl7.org/fhir/ValueSet/v3-SoftwareName')
No value set found at AuthoringDevice.manufacturerModelName (url = 'http://hl7.org/fhir/ValueSet/v3-ManufacturerModelName')
No value set found at AuthoringDevice.softwareName (url = 'http://hl7.org/fhir/ValueSet/v3-SoftwareName')
Exception in thread "main" java.lang.OutOfMemoryError: Java heap space
	at java.base/java.util.Arrays.copyOf(Arrays.java:3746)
	at java.base/java.lang.AbstractStringBuilder.ensureCapacityInternal(AbstractStringBuilder.java:172)
	at java.base/java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:538)
	at java.base/java.lang.StringBuilder.append(StringBuilder.java:174)
	at org.hl7.fhir.igtools.renderers.StructureDefinitionRenderer.generateReplacements(StructureDefinitionRenderer.java:702)
	at org.hl7.fhir.igtools.renderers.StructureDefinitionRenderer.dict(StructureDefinitionRenderer.java:665)
	at org.hl7.fhir.igtools.publisher.Publisher.generateOutputsStructureDefinition(Publisher.java:5919)
	at org.hl7.fhir.igtools.publisher.Publisher.generateHtmlOutputs(Publisher.java:5263)
	at org.hl7.fhir.igtools.publisher.Publisher.generate(Publisher.java:3876)
	at org.hl7.fhir.igtools.publisher.Publisher.createIg(Publisher.java:735)
	at org.hl7.fhir.igtools.publisher.Publisher.execute(Publisher.java:612)
	at org.hl7.fhir.igtools.publisher.Publisher.main(Publisher.java:6453)

**Comment by oliveregger** [comment]
see also [zulip](https://chat.fhir.org/#narrow/stream/198221-cda.2Fpublish/topic/java.20heap.20space.20error.20on.20rebuild)

**Comment by oliveregger** [comment]
issue is that the function generateReplacements in StructureDefinitionRenderer is stuck in a infinite loop:

Input id:
AD.usablePeriod 

Replacements:
[AD.useablePeriod -> AD.useablePeriodIVL_TS, AD.useablePeriod -> AD.useablePeriodEIVL_TS, AD.useablePeriod -> AD.useablePeriodPIVL_TS, AD.useablePeriod -> AD.useablePeriodSXPR_TS]

**Comment by oliveregger** [comment]
Input should actually be AD.usablePeriod[x], this is an error in the cda-core-2.0 model.
