### ISSUE TITLE
Generation of IG fails due to path to ig.ini

### ISSUE THREAD

**Issue by gabriel0316** [HL7/fhir-ig-publisher#421]
Taking https://github.com/HL7/cda-core-2.0 the creation of the IG fails with the following command

```
java -Xms2g -Xmx2g -jar org.hl7.fhir.publisher.jar -ig ./ig.ini
```

The output ends with the following error:

```
...
Exception generating page /tmp/CDA-core-2.0/./temp/pages/ncludes/artifacts.xml for ncludes/artifacts.xml in /tmp/CDA-core-2.0/./temp/pages: /tmp/CDA-core-2.0/./temp/pages/ncludes/artifacts.xml (No such file or directory) (05:58.0667)
Generating Summary Outputs                                                       (05:58.0668)
Publishing Content Failed: Template based HTML file index.html is missing source file index.md (07:19.0640)
                                                                                 (07:19.0641)  
Use -? to get command line help                                                  (07:19.0642)  
                                                                                 (07:19.0644)  
Stack Dump (for debugging):                                                      (07:19.0645)  
java.lang.Exception: Template based HTML file index.html is missing source file index.md       
        at org.hl7.fhir.igtools.publisher.Publisher.applyPageTemplate(Publisher.java:7358)     
        at org.hl7.fhir.igtools.publisher.Publisher.applyPageTemplate(Publisher.java:7372)     
        at org.hl7.fhir.igtools.publisher.Publisher.generateSummaryOutputs(Publisher.java:6885)
        at org.hl7.fhir.igtools.publisher.Publisher.generate(Publisher.java:5858)
        at org.hl7.fhir.igtools.publisher.Publisher.createIg(Publisher.java:1018)
        at org.hl7.fhir.igtools.publisher.Publisher.execute(Publisher.java:856)
        at org.hl7.fhir.igtools.publisher.Publisher.main(Publisher.java:10005)
```

Note, that the creation of the IG succeeds if the `./` is removed before `ig.ini` - hence, the command would look like:

```
java -Xms2g -Xmx2g -jar org.hl7.fhir.publisher.jar -ig ig.ini
```

**Comment by gabriel0316** [comment]
https://chat.fhir.org/#narrow/stream/179166-implementers/topic/CDA-core-2.2E0.20build.20error

**Comment by lmckenzi** [comment]
This is a low priority fix
