### ISSUE TITLE
exception with -go-publish and non-HL7 package id

### ISSUE THREAD

**Issue by bmilius-nmdp** [HL7/fhir-ig-publisher#451]
I want to create an IG using "myorg.org.myig" package name. e.g., "nmdp.org.myig". Everything builds fine until I run publisher with "-go-publish". Then publisher throws an exception. If I use an approved package id, e.g.,  hl7.fhir.dk.bob, it works fine but I then need to change the juristidiction and canonical.

```
$ java -jar publisher.jar -go-publish -source bobig -destination web-root -registry ig-registry/fhir-ig-list.json -history fhir-ig-history-template -milestone -temp temp
Exception in thread "main" java.lang.Error: Must be overridden
        at org.hl7.fhir.igtools.publisher.utils.WebSiteLayoutRulesProviders$DefaultNamingRulesProvider.getDestination(WebSiteLayoutRulesProviders.java:45)
        at org.hl7.fhir.igtools.publisher.utils.PublicationProcess.publishInner(PublicationProcess.java:121)
        at org.hl7.fhir.igtools.publisher.utils.PublicationProcess.publish(PublicationProcess.java:61)
        at org.hl7.fhir.igtools.publisher.Publisher.main(Publisher.java:9927)
```

see https://chat.fhir.org/#narrow/stream/215610-shorthand/topic/minimal.20publishable.20IG.20via.20sushi for example.

**Comment by lmckenzi** [comment]
Publisher now returns a clearer error message in this situation
