### ISSUE TITLE
1.1.122's IPA comparison with {current} crashes

### ISSUE THREAD

**Issue by vadi2** [HL7/fhir-ig-publisher#456]
I've enabled IPA comparison feature available in the latest 1.1.122 release [for my IG](https://build.fhir.org/ig/HL7/fhir-ichom-breast-cancer-ig/), but it is unfortunately crashing:

```
Validating Conformance Resources                                                 (00:42.598)
java.lang.NullPointerException: Cannot invoke "String.replace(java.lang.CharSequence, java.lang.CharSequence)" because "a" is null
        at org.hl7.fhir.utilities.Utilities.path(Utilities.java:614)
        at org.hl7.fhir.igtools.publisher.comparators.IpaComparator.startChecks(IpaComparator.java:201)
        at org.hl7.fhir.igtools.publisher.Publisher.checkConformanceResources(Publisher.java:4831)
        at org.hl7.fhir.igtools.publisher.Publisher.loadConformance(Publisher.java:4743)
        at org.hl7.fhir.igtools.publisher.Publisher.createIg(Publisher.java:1005)
        at org.hl7.fhir.igtools.publisher.Publisher.execute(Publisher.java:855)
        at org.hl7.fhir.igtools.publisher.Publisher.main(Publisher.java:10193)
Validating Resources                                                             (00:45.804)
```

**Comment by vadi2** [comment]
The issue is using ipa-comparison `{current}`. Using `{last}` instead works fine.
