### ISSUE TITLE
R4B type parsing broken in 1.1.128

### ISSUE THREAD

**Issue by vadi2** [HL7/fhir-ig-publisher#489]
I'm still having an issue with the publisher choking on despite using the latest 1.1.128. IG is [located here](https://github.com/HL7/fhir-ichom-breast-cancer-ig).

Is there something misconfigured on my side?

```
Checking internet connection...
Online

FHIR IG Publisher Version 1.1.128 (Git# 89f581f54afc). Built 2022-08-03T17:24:21.398Z (18 days old)
Detected Java version: 16.0.2 from /Library/Java/JavaVirtualMachines/temurin-16.jdk/Contents/Home on Mac OS X/x86_64 (64bit). 4096
MB available                                                                                                                      dir = /Users/320128457/Programs/BreastCancer-ICHOM, path = /Users/320128457/Programs/miniconda3/bin:/Users/320128457/Programs/goog
le-cloud-sdk/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/share/dotnet:~/.dotnet/tools:/Library/Apple/usr/bin:/Users/320128457/Programs/miniconda3/bin:/Users/320128457/Programs/google-cloud-sdk/bin:/Users/320128457/.dotnet/tools:/Users/320128457/.dotnet/tools                                                                                                                    Parameters: -ig .
Start Clock @ Monday, 22 August 2022 at 08:32:34 Central European Summer Time (2022-08-22T08:32:34+02:00)

API keys loaded from /Users/320128457/fhir-api-keys.ini                          (00:00.045)
Package Cache: /Users/320128457/.fhir/packages                                   (00:00.052)
Run Sushi on /Users/320128457/Programs/BreastCancer-ICHOM                        (00:00.053)
Sushi: info  Running SUSHI v2.6.0 (implements FHIR Shorthand specification v2.0.0) (00:01.552)
Sushi: info  Arguments:                                                          (00:01.553)
Sushi: info    --out /Users/320128457/Programs/BreastCancer-ICHOM                (00:01.554)
Sushi: info    /Users/320128457/Programs/BreastCancer-ICHOM                      (00:01.555)
Sushi: (node:28046) Warning: Accessing non-existent property 'INVALID_ALT_NUMBER' of module exports inside circular dependency (00
:01.587)                                                                                                                          Sushi: (Use `node --trace-warnings ...` to show where the warning was created)   (00:01.592)
Sushi: (node:28046) Warning: Accessing non-existent property 'INVALID_ALT_NUMBER' of module exports inside circular dependency (00
:01.594)                                                                                                                          Sushi: info  Using configuration file: /Users/320128457/Programs/BreastCancer-ICHOM/sushi-config.yaml (00:01.970)
Sushi: info  Importing FSH text...                                               (00:01.983)
Sushi: info  Preprocessed 18 documents with 25 aliases.                          (00:02.310)
Sushi: info  Imported 84 definitions and 46 instances.                           (00:02.426)
Sushi: info  Checking local cache for hl7.fhir.r4.core#4.0.1...                  (00:02.427)
Sushi: info  Found hl7.fhir.r4.core#4.0.1 in local cache.                        (00:04.871)
Sushi: info  Loaded package hl7.fhir.r4.core#4.0.1                               (00:04.872)
Sushi: info  Converting FSH to FHIR resources...                                 (00:04.932)
Sushi: info  Converted 36 FHIR StructureDefinitions.                             (00:05.552)
Sushi: info  Converted 11 FHIR CodeSystems.                                      (00:05.655)
Sushi: info  Converted 37 FHIR ValueSets.                                        (00:05.676)
Sushi: info  Converted 46 FHIR instances.                                        (00:09.552)
Sushi: info  Exporting FHIR resources as JSON...                                 (00:09.640)
Sushi: info  Exported 130 FHIR resources as JSON.                                (00:09.810)
Sushi: info  Assembling Implementation Guide sources...                          (00:09.811)
Sushi: info  Generated ImplementationGuide-hl7.fhir.uv.ichom.breastcancer.json   (00:09.820)
Sushi: info  Assembled Implementation Guide sources; ready for IG Publisher.     (00:09.821)
Sushi:                                                                           (00:09.822)
Sushi: ========================= SUSHI RESULTS ===========================       (00:09.823)
Sushi: |  -------------------------------------------------------------  |       (00:09.825)
Sushi: | |    Profiles   |  Extensions  |   Logicals   |   Resources   | |       (00:09.827)
Sushi: | |-------------------------------------------------------------| |       (00:09.827)
Sushi: | |      33       |      3       |      0       |       0       | |       (00:09.828)
Sushi: |  -------------------------------------------------------------  |       (00:09.829)
Sushi: |  -------------------------------------------------------------  |       (00:09.830)
Sushi: | |      ValueSets     |    CodeSystems    |     Instances      | |       (00:09.831)
Sushi: | |-------------------------------------------------------------| |       (00:09.832)
Sushi: | |         37         |        11         |         46         | |       (00:09.832)
Sushi: |  -------------------------------------------------------------  |       (00:09.833)
Sushi: |                                                                 |       (00:09.833)
Sushi: ===================================================================       (00:09.834)
Sushi: | You are dolphinitely doing great!      0 Errors      0 Warnings |       (00:09.835)
Sushi: ===================================================================       (00:09.835)
Sushi: |    You are using SUSHI version 2.6.0, but the latest stable     |       (00:09.836)
Sushi: |  release is version 2.6.1. To install the latest release, run:  |       (00:09.837)
Sushi: |                    npm install -g fsh-sushi                     |       (00:09.837)
Sushi: ===================================================================       (00:09.838)
Sushi:                                                                           (00:09.839)
Load Template from hl7.fhir.template#current                                     (00:10.605)
 Load Template from hl7.base.template#current                                    (00:12.962)
  Load Template from fhir.base.template#current                                  (00:13.113)

onLoad.findSpreadsheets:

onLoad.updateIg:
     [xslt] Processing /Users/320128457/Programs/BreastCancer-ICHOM/template/onLoad-ig-working.xml to /Users/320128457/Programs/Br
eastCancer-ICHOM/template/onLoad-ig-updated.xml                                                                                        [xslt] Loading stylesheet /Users/320128457/Programs/BreastCancer-ICHOM/template/scripts/onLoad.xslt

onLoad.extend:

onLoad:
Root directory: /Users/320128457/Programs/BreastCancer-ICHOM                     (00:17.766)
Core Package hl7.fhir.r4.core#4.0.1
Terminology Cache is at /Users/320128457/Programs/BreastCancer-ICHOM/input-cache/txcache. 20 files in cache (00:28.249)
Connect to Terminology Server at http://tx.fhir.org                              (00:28.251)
Load Package hl7.fhir.pubpack#0.1.1
Load Package hl7.fhir.xver-extensions#0.0.11
Load Package hl7.terminology.r4#3.1.0
Load R5 ExtensionsPublishing Content Failed: Unknown FHIRVersion code '4.3.0-CIBUILD'              (01:09.744)
                                                                                 (01:09.745)
Use -? to get command line help                                                  (01:09.746)
                                                                                 (01:09.747)
Stack Dump (for debugging):                                                      (01:09.748)
java.lang.IllegalArgumentException: Unknown FHIRVersion code '4.3.0-CIBUILD'
        at org.hl7.fhir.r5.model.Enumerations$FHIRVersionEnumFactory.fromCode(Enumerations.java:7207)
        at org.hl7.fhir.r5.model.Enumerations$FHIRVersionEnumFactory.fromCode(Enumerations.java:7094)
        at org.hl7.fhir.r5.formats.JsonParser.parseEnumeration(JsonParser.java:73)
        at org.hl7.fhir.r5.formats.JsonParser.parseStructureDefinitionProperties(JsonParser.java:27398)
        at org.hl7.fhir.r5.formats.JsonParser.parseStructureDefinition(JsonParser.java:27317)
        at org.hl7.fhir.r5.formats.JsonParser.parseResource(JsonParser.java:32271)
        at org.hl7.fhir.r5.formats.JsonParserBase.parse(JsonParserBase.java:133)
        at org.hl7.fhir.r5.conformance.R5ExtensionsLoader.loadR5Extensions(R5ExtensionsLoader.java:47)
        at org.hl7.fhir.igtools.publisher.Publisher.initializeFromIg(Publisher.java:2727)
        at org.hl7.fhir.igtools.publisher.Publisher.initialize(Publisher.java:2198)
        at org.hl7.fhir.igtools.publisher.Publisher.execute(Publisher.java:865)
        at org.hl7.fhir.igtools.publisher.Publisher.main(Publisher.java:10297)
```

**Comment by grahamegrieve** [comment]
so this works for me. what happens if you clear your fhir package cache?

**Comment by vadi2** [comment]
That worked, thanks!
