### ISSUE TITLE
[BUG]: ./_genonce.sh all of sudden returns error: Could not locate the included file 'StructureDefinition-CareTeamUp-dict-diff.xhtml'

### ISSUE THREAD

**Issue by rrapio** [HL7/fhir-ig-publisher#541]
This is a reopening of #537. The workaround proposed by @lquanx do solve the problem, but I can't really use it because I have a custom template, so I can't use `template = fhir.base.template#0.2.2` in `ig.ini`.

My ig.ini:

```ini
[IG]
ig = fsh-generated/resources/ImplementationGuide-fhir.pt.uphill.json
template = uh-template
```

My error:

```log
Run jekyll: jekyll build --destination "/home/devuser/patient-integration-ig/output" (in folder /home/devuser/patient-integration-ig/temp) (01:11.0102)
Jekyll: Source: /home/devuser/patient-integration-ig/temp                        (01:11.0426)
Jekyll: Generating...                                                            (01:11.0427)
Jekyll has failed. Complete output from running Jekyll:   Liquid Exception: Could not locate the included file 'StructureDefinition-CareTeamUp-dict-diff.xhtml' in any of ["/home/devuser/patient-integration-ig/temp/_includes"]. Ensure it exists in one of those directories and, if it is a symlink, does not p (01:13.0646)
Note: Check that Jekyll is installed correctly                                   (01:13.0648)
Publishing Content Failed: Process exited with an error: 1 (Exit value: 1)       (01:13.0669)
                                                                                 (01:13.0670)
Use -? to get command line help                                                  (01:13.0671)
                                                                                 (01:13.0673)
Stack Dump (for debugging):                                                      (01:13.0675)
org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1)
        at org.apache.commons.exec.DefaultExecutor.executeInternal(DefaultExecutor.java:404)
        at org.apache.commons.exec.DefaultExecutor.execute(DefaultExecutor.java:166)
        at org.apache.commons.exec.DefaultExecutor.execute(DefaultExecutor.java:153)
        at org.hl7.fhir.igtools.publisher.Publisher.runJekyll(Publisher.java:6653)
        at org.hl7.fhir.igtools.publisher.Publisher.runTool(Publisher.java:6565)
        at org.hl7.fhir.igtools.publisher.Publisher.generate(Publisher.java:5918)
        at org.hl7.fhir.igtools.publisher.Publisher.createIg(Publisher.java:1018)
        at org.hl7.fhir.igtools.publisher.Publisher.execute(Publisher.java:856)
        at org.hl7.fhir.igtools.publisher.Publisher.main(Publisher.java:10005)
```

With the following `ig.ini`, I don't get any errors:

```ini
[IG]
ig = fsh-generated/resources/ImplementationGuide-fhir.pt.uphill.json
template = fhir.base.template#0.2.2
```

**Comment by lmckenzi** [comment]
Are you using the most recent version of the IG Publisher?  If you're using the #current template, you'll need to keep up with the publisher.

**Comment by rrapio** [comment]
Updating the publisher fixed the problem, thank you!
