### ISSUE TITLE
IG Publisher cannot generate snapshot table for Logical inheritance parent-child-grandchild

### ISSUE THREAD

**Issue by Shaumik-Ashraf** [HL7/fhir-ig-publisher#544]
There is a bug in the IG publisher tool when using sushi fsh to define Logicals with inheritance in an IG. The sushi compiler passes the FSH structure and the json artifacts pass the inferno validator. I couldn't find anything against this kind of model in the FHIR spec either. Please fix the bug or give me some advice if I'm missing something. I put some debugging info below:

### Steps to reproduce:
- `sushi -i`
- Press enter for prompts
- Add the following content to input/fsh/patient.fsh
```
Logical: Foo
* a 1..1 string "a" "parent"

Logical: Boo
Parent: Foo
* b 1..1 string "b" "child"

Logical: Goo
Parent: Boo
* c 1..1 string "c" "grandchild"
```
- `./_updatePublisher.sh`
- Press 'y' for prompts
- `./_genonce.sh`

### Result - exception with stacktrace:
```
Stack Dump (for debugging):                                                      (00:10.659)
java.lang.Exception: Error generating snapshot for ~/workspace/logical-bug/LogicalBug/fsh-generated/resources/StructureDefinition-Goo(Goo): Adding wrong path - outcome.getPath() = Boo, resultPathBase = Foo
	at org.hl7.fhir.igtools.publisher.Publisher.generateSnapshots(Publisher.java:5803)
	at org.hl7.fhir.igtools.publisher.Publisher.loadConformance(Publisher.java:4959)
	at org.hl7.fhir.igtools.publisher.Publisher.createIg(Publisher.java:1085)
	at org.hl7.fhir.igtools.publisher.Publisher.execute(Publisher.java:914)
	at org.hl7.fhir.igtools.publisher.Publisher.main(Publisher.java:10727)
Caused by: org.hl7.fhir.exceptions.DefinitionException: Adding wrong path - outcome.getPath() = Boo, resultPathBase = Foo
	at org.hl7.fhir.r5.conformance.ProfileUtilities.processPaths(ProfileUtilities.java:1222)
	at org.hl7.fhir.r5.conformance.ProfileUtilities.generateSnapshot(ProfileUtilities.java:724)
	at org.hl7.fhir.igtools.publisher.Publisher.generateSnapshot(Publisher.java:5883)
	at org.hl7.fhir.igtools.publisher.Publisher.generateSnapshots(Publisher.java:5801)
	... 4 more
```

### Expected - IG to compile

**Comment by Shaumik-Ashraf** [comment]
Update: Snapshot table generation for Logical models with a Parent model seem broken entirely (even for 2-generation parent-child logicals)

**Comment by grahamegrieve** [comment]
what version IG publisher are you using, and please attach the structure definitions to this task

**Comment by Shaumik-Ashraf** [comment]
FHIR IG Publisher Version 1.2.12 (Git# 6fecde31ce6f). Built 2022-10-28T19:22:25.188Z (5 days old)
Detected Java version: 11.0.15 from /Library/Java/JavaVirtualMachines/temurin-11.jdk/Contents/Home on Mac OS X/aarch64 (64bit). 8192MB available

Structure definitions in zip folder:
[resources.zip](https://github.com/HL7/fhir-ig-publisher/files/9923810/resources.zip)

**Comment by grahamegrieve** [comment]
fixed next release
