### ISSUE TITLE
1.2.24 issue

### ISSUE THREAD

**Issue by lquanx** [HL7/fhir-ig-publisher#571]
Hi, The version `1.2.23` worked fine. But the latest version `1.2.24` throws the bellow error.
```
onGenerate:
Publishing Content Failed: Not a JSON Object: null                               (00:40.573)
                                                                                 (00:40.573)
Use -? to get command line help                                                  (00:40.574)
                                                                                 (00:40.574)
Stack Dump (for debugging):                                                      (00:40.574)
java.lang.IllegalStateException: Not a JSON Object: null
        at com.google.gson.JsonElement.getAsJsonObject(JsonElement.java:91)
        at org.hl7.fhir.r5.formats.JsonParser.parseOperationOutcomeProperties(JsonParser.java:23994)
        at org.hl7.fhir.r5.formats.JsonParser.parseOperationOutcome(JsonParser.java:23985)
        at org.hl7.fhir.r5.formats.JsonParser.parseResource(JsonParser.java:33803)
        at org.hl7.fhir.r5.formats.JsonParserBase.parse(JsonParserBase.java:133)
        at org.hl7.fhir.igtools.templates.Template.runScriptTarget(Template.java:223)
        at org.hl7.fhir.igtools.templates.Template.beforeGenerateEvent(Template.java:385)
        at org.hl7.fhir.igtools.publisher.Publisher.templateBeforeGenerate(Publisher.java:4433)
        at org.hl7.fhir.igtools.publisher.Publisher.generate(Publisher.java:6348)
        at org.hl7.fhir.igtools.publisher.Publisher.createIg(Publisher.java:1084)
        at org.hl7.fhir.igtools.publisher.Publisher.execute(Publisher.java:902)
        at org.hl7.fhir.igtools.publisher.Publisher.main(Publisher.java:10754)
```
I'm wondering is it because it is using `.r5.formats` ? Our IG is based on r4. I'm thinking there shouldn't be anything about r5. Isn't it ?
Thanks

**Comment by grahamegrieve** [comment]
The IG publisher is entirely R5 based internally. This is an issue in the template being discussed here: https://chat.fhir.org/#narrow/stream/179252-IG-creation/topic/Not.20a.20JSON.20Object.3A.20null

**Comment by lquanx** [comment]
Thanks for the quick reply
