### ISSUE TITLE
Empty value in onGenerate-validation.json

### ISSUE THREAD

**Issue by qligier** [HL7/fhir-ig-publisher#572]
Building [my IG](https://github.com/CARA-ch/ch-emed-epr) ([build.log](http://build.fhir.org/ig/CARA-ch/ch-emed-epr/branches/master/failure/build.log)) with the publisher v1.2.24 fails with an IllegalStateException. It was working fine with v1.2.23.

```log
onGenerate.extend:

onGenerate:
Publishing Content Failed: Not a JSON Object: null                               (01:43.742)
                                                                                 (01:43.742)
Use -? to get command line help                                                  (01:43.743)
                                                                                 (01:43.743)
Stack Dump (for debugging):                                                      (01:43.744)
java.lang.IllegalStateException: Not a JSON Object: null
        at com.google.gson.JsonElement.getAsJsonObject(JsonElement.java:91)
        at org.hl7.fhir.r5.formats.JsonParser.parseOperationOutcomeProperties(JsonParser.java:23994)
        at org.hl7.fhir.r5.formats.JsonParser.parseOperationOutcome(JsonParser.java:23985)
        at org.hl7.fhir.r5.formats.JsonParser.parseResource(JsonParser.java:33803)
        at org.hl7.fhir.r5.formats.JsonParserBase.parse(JsonParserBase.java:133)
        at org.hl7.fhir.igtools.templates.Template.runScriptTarget(Template.java:223)
        at org.hl7.fhir.igtools.templates.Template.beforeGenerateEvent(Template.java:385)
        at org.hl7.fhir.igtools.publisher.Publisher.templateBeforeGenerate(Publisher.java:4433)
        at org.hl7.fhir.igtools.publisher.Publisher.generate(Publisher.java:6348)
        at org.hl7.fhir.igtools.publisher.Publisher.createIg(Publisher.java:1084)
        at org.hl7.fhir.igtools.publisher.Publisher.execute(Publisher.java:902)
        at org.hl7.fhir.igtools.publisher.Publisher.main(Publisher.java:10754)
```

It happens when parsing the content of `/template/onGenerate-validation.json`, which contains an extra comma at the end:
```json
{"resourceType":"OperationOutcome","issue":[
      
{"severity":"warning","code":"invariant","details":{"text":"Unable to find ImplementationGuide.definition.resource.description for the resource ValueSet/substance-admin-substitution-code.  Descriptions are strongly encouraged if they cannot be inferred from the resource to allow proper population of the artifact list."},"location":["ImplementationGuide.definition.resource[39]"]}
,
{"severity":"warning","code":"invariant","details":{"text":"Unable to find ImplementationGuide.definition.resource.description for the resource Medication/Triatec.  Descriptions are strongly encouraged if they cannot be inferred from the resource to allow proper population of the artifact list."},"location":["ImplementationGuide.definition.resource[44]"]}
,]}
```

I'm not sure what part generates this file.

**Comment by qligier** [comment]
It seems fixed with release 1.2.25, I'm able to build it again.
