### ISSUE TITLE
Unknown Type "Expression" when example questionnaire is down converted to STU3

### ISSUE THREAD

**Issue by brianpos** [HL7/fhir-ig-publisher#61]
When an IG (such as the SCD IG) includes an example that includes an R5 extension data type that wasn't available in STU3 then the conversion into R3 format for registry.fhir.org fails, and so writes to the stderr stream.
The build continues anyway to completion and reports success.
(However my CI build infrastructure sees the stderr content and reports the build as a fail)

Branch with the issue: https://github.com/HL7/sdc/tree/master
(but I found it on my own private IG doing essentially the same thing)

```
Can't store Questionnaire-questionnaire-sdc-profile-example-PHQ9 in R3 format for registry.fhir.org (00:41.0874)
org.hl7.fhir.exceptions.FHIRException: Unknown type Expression
	at org.hl7.fhir.convertors.VersionConvertor_30_50.convertType(VersionConvertor_30_50.java:3187)
	at org.hl7.fhir.convertors.VersionConvertor_30_50.convertExtension(VersionConvertor_30_50.java:417)
	at org.hl7.fhir.convertors.VersionConvertor_30_50.copyElement(VersionConvertor_30_50.java:102)
	at org.hl7.fhir.convertors.conv30_50.Questionnaire30_50.convertQuestionnaireItemComponent(Questionnaire30_50.java:128)
	at org.hl7.fhir.convertors.conv30_50.Questionnaire30_50.convertQuestionnaireItemComponent(Questionnaire30_50.java:161)
	at org.hl7.fhir.convertors.conv30_50.Questionnaire30_50.convertQuestionnaire(Questionnaire30_50.java:119)
	at org.hl7.fhir.convertors.VersionConvertor_30_50.convertResource(VersionConvertor_30_50.java:4850)
	at org.hl7.fhir.igtools.publisher.Publisher.generateRegistryUploadZip(Publisher.java:4728)
	at org.hl7.fhir.igtools.publisher.Publisher.generateZips(Publisher.java:4613)
	at org.hl7.fhir.igtools.publisher.Publisher.generate(Publisher.java:4364)
	at org.hl7.fhir.igtools.publisher.Publisher.createIg(Publisher.java:815)
	at org.hl7.fhir.igtools.publisher.Publisher.execute(Publisher.java:665)
	at org.hl7.fhir.igtools.publisher.Publisher.main(Publisher.java:6945)
```

**Comment by lmckenzi** [comment]
@brianpos is this still an issue?

**Comment by lmckenzi** [comment]
This issue doesn't seem to be happening in the current build, so closing.
