### ISSUE TITLE
Error while generating IG on file path 

### ISSUE THREAD

**Issue by wylem-bars** [HL7/fhir-ig-publisher#632]
Hello, 

I get the following error when compiling my IG with the new version 1.2.42 (previously working just fine with 1.2.40 and bellow) : 

`java.nio.file.InvalidPathException: Illegal char <:> at index 59: C:\Users\wylem\workspace\FYRSTAIN\IG\template\C:\Users\wylem\workspace\FYRSTAIN\IG\template\onLoad-ig-working.json
        at java.base/sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:182)
        at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:153)
        at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77)
        at java.base/sun.nio.fs.WindowsPath.parse(WindowsPath.java:92)
        at java.base/sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:232)
        at java.base/java.nio.file.Path.of(Path.java:147)
        at org.hl7.fhir.utilities.Utilities.path(Utilities.java:648)
        at org.hl7.fhir.igtools.templates.Template.runScriptTarget(Template.java:194)
        at org.hl7.fhir.igtools.templates.Template.onLoadEvent(Template.java:366)
        at org.hl7.fhir.igtools.publisher.Publisher.initializeFromIg(Publisher.java:2473)
        at org.hl7.fhir.igtools.publisher.Publisher.initialize(Publisher.java:2247)
        at org.hl7.fhir.igtools.publisher.Publisher.execute(Publisher.java:899)
        at org.hl7.fhir.igtools.publisher.Publisher.main(Publisher.java:10981)`

As you can see, there is now the base path for the file twice in the final path for the file onLoad-ig-working.json. 
I followed the stack and ended up on this code : 

`    String sfn = Utilities.path(templateDir, target + "-ig-working.");
    String fn = Utilities.path(templateDir, target + "-ig-updated.");
    File jsonIg = new File(Utilities.path(templateDir, sfn +"json"));
    File xmlIg = new File(Utilities.path(templateDir, sfn + "xml"));`

We can see that the templateDir is indeed used twice but this code is old and never raised this issue. However I saw that the version of the core library was bumped up to 5.6.109. This is where the **Utilities** class comes from. My guess is that there was some kind of "counter bug" canceling this issue in the past and that the update of the library resolved it and so we have the problem just now. 

Do you think I'm onto something or am completely offtrack ? Is it something that is planned to fix (I see that a 1.2.43 is on the way to fix some critical issues) ?

Thanks in advance,

Wylem

**Comment by grahamegrieve** [comment]
Yes. It popped up because of new security checks we made

**Comment by wylem-bars** [comment]
Thanks a lot @grahamegrieve  !
