### ISSUE TITLE
java.nio.file.InvalidPathException:

### ISSUE THREAD

**Issue by FranSSAS01** [HL7/fhir-ig-publisher#643]
Installing hl7.fhir.cl.ssasur.asv#dev to the package cache
  Fetching:
...
  Installing: ... done.
Checking Output HTML                                                             (03:21.864)
found 1807 files                                                                 (03:21.915)
........................................
..........Publishing Content Failed: Illegal char <:> at index 134: C:\xxxx\xxxxxx\xxxxxx\SUSHI\asv\output\StructureDefinition-CdrAlturaEdadInfantil-definitions.html#key_Observation.category:VSCat (03:44.196)
                                                                                 (03:44.198)
Use -? to get command line help                                                  (03:44.198)
                                                                                 (03:44.199)
Stack Dump (for debugging):                                                      (03:44.200)
java.nio.file.InvalidPathException: Illegal char <:> at index 134: C:\XXXX\xxxx\xxxx\SUSHI\asv\output\StructureDefinition-CdrAlturaEdadInfantil-definitions.html#key_Observation.category:VSCat
        at java.base/sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:182)
        at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:153)
        at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77)
        at java.base/sun.nio.fs.WindowsPath.parse(WindowsPath.java:92)
        at java.base/sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:229)
        at java.base/java.nio.file.Path.of(Path.java:147)
        at org.hl7.fhir.utilities.Utilities.path(Utilities.java:648)
        at org.hl7.fhir.igtools.publisher.HTMLInspector.checkResolveLink(HTMLInspector.java:649)
        at org.hl7.fhir.igtools.publisher.HTMLInspector.checkLinks(HTMLInspector.java:542)
        at org.hl7.fhir.igtools.publisher.HTMLInspector.checkLinks(HTMLInspector.java:557)
        at org.hl7.fhir.igtools.publisher.HTMLInspector.checkLinks(HTMLInspector.java:557)
        at org.hl7.fhir.igtools.publisher.HTMLInspector.checkLinks(HTMLInspector.java:557)
        at org.hl7.fhir.igtools.publisher.HTMLInspector.checkLinks(HTMLInspector.java:557)
        at org.hl7.fhir.igtools.publisher.HTMLInspector.checkLinks(HTMLInspector.java:557)
        at org.hl7.fhir.igtools.publisher.HTMLInspector.checkLinks(HTMLInspector.java:557)
        at org.hl7.fhir.igtools.publisher.HTMLInspector.checkLinks(HTMLInspector.java:557)
        at org.hl7.fhir.igtools.publisher.HTMLInspector.checkLinks(HTMLInspector.java:557)
        at org.hl7.fhir.igtools.publisher.HTMLInspector.checkLinks(HTMLInspector.java:557)
        at org.hl7.fhir.igtools.publisher.HTMLInspector.checkLinks(HTMLInspector.java:557)
        at org.hl7.fhir.igtools.publisher.HTMLInspector.checkLinks(HTMLInspector.java:557)
        at org.hl7.fhir.igtools.publisher.HTMLInspector.checkLinks(HTMLInspector.java:557)
        at org.hl7.fhir.igtools.publisher.HTMLInspector.checkLinks(HTMLInspector.java:557)
        at org.hl7.fhir.igtools.publisher.HTMLInspector.checkLinks(HTMLInspector.java:557)
        at org.hl7.fhir.igtools.publisher.HTMLInspector.checkLinks(HTMLInspector.java:557)
        at org.hl7.fhir.igtools.publisher.HTMLInspector.check(HTMLInspector.java:288)
        at org.hl7.fhir.igtools.publisher.Publisher.generate(Publisher.java:6627)
        at org.hl7.fhir.igtools.publisher.Publisher.createIg(Publisher.java:1088)
        at org.hl7.fhir.igtools.publisher.Publisher.execute(Publisher.java:906)
        at org.hl7.fhir.igtools.publisher.Publisher.main(Publisher.java:10990)

**Comment by lmckenzi** [comment]
@FranSSAS01 Is this still an issue with the most recent version of the publisher?

**Comment by lmckenzi** [comment]
Poke

**Comment by FranSSAS01** [comment]
No, this issue is of the version 1.2.51

**Comment by lmckenzi** [comment]
Closing as the current release works.
