### ISSUE TITLE
Is it not possible to use an OID as the URL for a ValueSet when working with  publisher?

### ISSUE THREAD

**Issue by kalleo1996** [HL7/fhir-ig-publisher#703]
I am currently using "no-basis-Practitioner" as a reference , which has a binding to the ValueSet with the URN: "urn:oid:2.16.578.1.12.4.1.1.9060". As far as my understanding goes, using an OID for the URL of a ValueSet is not incorrect, since the type of URL is URI. However, I would like to inquire if there is any action that can be taken from the publisher's end to address this matter?

java.nio.file.InvalidPathException: Illegal char <:> at index 48: path\output\urn:oid:2.16.578.1.12.4.1.1.9060
        at java.base/sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:182)
        at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:153)
        at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77)
        at java.base/sun.nio.fs.WindowsPath.parse(WindowsPath.java:92)
        at java.base/sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:229)
        at java.base/java.nio.file.Path.of(Path.java:147)
        at org.hl7.fhir.utilities.PathBuilder.checkPathIsChildOfTarget(PathBuilder.java:142)
        at org.hl7.fhir.utilities.PathBuilder.buildPath(PathBuilder.java:129)
        at org.hl7.fhir.utilities.Utilities.path(Utilities.java:628)
        at org.hl7.fhir.igtools.publisher.HTMLInspector.checkResolveLink(HTMLInspector.java:703)
        at org.hl7.fhir.igtools.publisher.HTMLInspector.checkLinks(HTMLInspector.java:542)
        at org.hl7.fhir.igtools.publisher.HTMLInspector.checkLinks(HTMLInspector.java:557)
        at org.hl7.fhir.igtools.publisher.HTMLInspector.checkLinks(HTMLInspector.java:557)
        at org.hl7.fhir.igtools.publisher.HTMLInspector.checkLinks(HTMLInspector.java:557)
        at org.hl7.fhir.igtools.publisher.HTMLInspector.checkLinks(HTMLInspector.java:557)
        at org.hl7.fhir.igtools.publisher.HTMLInspector.checkLinks(HTMLInspector.java:557)
        at org.hl7.fhir.igtools.publisher.HTMLInspector.checkLinks(HTMLInspector.java:557)
        at org.hl7.fhir.igtools.publisher.HTMLInspector.checkLinks(HTMLInspector.java:557)
        at org.hl7.fhir.igtools.publisher.HTMLInspector.checkLinks(HTMLInspector.java:557)
        at org.hl7.fhir.igtools.publisher.HTMLInspector.checkLinks(HTMLInspector.java:557)
        at org.hl7.fhir.igtools.publisher.HTMLInspector.checkLinks(HTMLInspector.java:557)
        at org.hl7.fhir.igtools.publisher.HTMLInspector.checkLinks(HTMLInspector.java:557)
        at org.hl7.fhir.igtools.publisher.HTMLInspector.checkLinks(HTMLInspector.java:557)
        at org.hl7.fhir.igtools.publisher.HTMLInspector.checkLinks(HTMLInspector.java:557)
        at org.hl7.fhir.igtools.publisher.HTMLInspector.checkLinks(HTMLInspector.java:557)
        at org.hl7.fhir.igtools.publisher.HTMLInspector.check(HTMLInspector.java:288)
        at org.hl7.fhir.igtools.publisher.Publisher.generate(Publisher.java:7140)
        at org.hl7.fhir.igtools.publisher.Publisher.createIg(Publisher.java:1119)
        at org.hl7.fhir.igtools.publisher.Publisher.execute(Publisher.java:932)
        at org.hl7.fhir.igtools.publisher.Publisher.main(Publisher.java:11600)

**Comment by grahamegrieve** [comment]
please provide a link to a GitHub repository that demonstrates this problem in practice

**Comment by kalleo1996** [comment]
Hello, I wanted to share the [link ](https://github.com/kalleo1996/IGNoPractionerIssue)to an example project with you. When you run it, you will encounter the above problem. Please inform me if there is anything that can be addressed regarding this issue on the publisher's side. Additionally, this example is based of no-basis-Practioner , and  [this is the Link for no-basis Repo](https://github.com/HL7Norway/basisprofiler-r4) . though it is bind to this Valueset  in the no-basis-Repo ,as follows 
`      <binding>
        <strength value="preferred" />
        <valueSet value="urn:oid:2.16.578.1.12.4.1.1.9060" />
      </binding>
`
 **there is no Valueset with oid urn:oid:2.16.578.1.12.4.1.1.9060 exists inside the no-basis repo** .

**Comment by kalleo1996** [comment]
Yes it it is a unpublished/undefined value set , thank you for the reply .

**Comment by lmckenzi** [comment]
Problem where hyperlinks were being created for OIDs is now fixed.
