### ISSUE TITLE
narrative generation doesn't like empty required boolean

### ISSUE THREAD

**Issue by JohnMoehrke** [HL7/fhir-ig-publisher#801]
I have an IG where I can not populate the Immunization.primarySource; so I add a data-absent-reason. But the IG publisher seems to NPE on this

Error Generating Narrative for Immunization/28653: Cannot invoke "java.lang.Boolean.toString()" because the return value of "org.hl7.fhir.r5.model.BooleanType.getValue()" is null
java.lang.NullPointerException: Cannot invoke "java.lang.Boolean.toString()" because the return value of "org.hl7.fhir.r5.model.BooleanType.getValue()" is null
        at org.hl7.fhir.r5.renderers.ProfileDrivenRenderer.renderLeaf(ProfileDrivenRenderer.java:391)
        at org.hl7.fhir.r5.renderers.ProfileDrivenRenderer.generateElementByProfile(ProfileDrivenRenderer.java:851)
        at org.hl7.fhir.r5.renderers.ProfileDrivenRenderer.generateForProperty(ProfileDrivenRenderer.java:795)
        at org.hl7.fhir.r5.renderers.ProfileDrivenRenderer.generateByProfile(ProfileDrivenRenderer.java:776)
        at org.hl7.fhir.r5.renderers.ProfileDrivenRenderer.render(ProfileDrivenRenderer.java:130)
        at org.hl7.fhir.r5.renderers.ProfileDrivenRenderer.render(ProfileDrivenRenderer.java:101)
        at org.hl7.fhir.r5.renderers.ResourceRenderer.build(ResourceRenderer.java:76)
        at org.hl7.fhir.r5.renderers.BundleRenderer.render(BundleRenderer.java:343)
        at org.hl7.fhir.igtools.publisher.Publisher.getXhtml(Publisher.java:11700)
        at org.hl7.fhir.igtools.publisher.Publisher.saveDirectResourceOutputs(Publisher.java:10937)
        at org.hl7.fhir.igtools.publisher.Publisher.generateHtmlOutputs(Publisher.java:10134)
        at org.hl7.fhir.igtools.publisher.Publisher.generate(Publisher.java:7392)
        at org.hl7.fhir.igtools.publisher.Publisher.createIg(Publisher.java:1139)
        at org.hl7.fhir.igtools.publisher.Publisher.execute(Publisher.java:968)
        at org.hl7.fhir.igtools.publisher.Publisher.main(Publisher.java:12304)
P

**Comment by lmckenzi** [comment]
Fixed
