### ISSUE TITLE
Continuous Build blows up on second run

### ISSUE THREAD

**Issue by costateixeira** [HL7/fhir-ig-publisher#81]
When you use the _buildContinuous option with sample-ig, it builds successfully, then after 5 seconds automatically retries and fails with the following error:
`Watching for changes on a 5sec cycle
Resource StructureDefinition/myObservation not defined
Resources: StructureDefinition/mypatient, Patient/example, StructureDefinition/ext-myExtension, StructureDefinition/mypractitioner
Publishing Content Failed: Invalid - see reasons

Use -? to get command line help

Stack Dump (for debugging):
java.lang.Exception: Invalid - see reasons
        at org.hl7.fhir.igtools.publisher.Publisher.load(Publisher.java:2831)
        at org.hl7.fhir.igtools.publisher.Publisher.execute(Publisher.java:676)
        at org.hl7.fhir.igtools.publisher.Publisher.main(Publisher.java:6937)`

**Comment by lmckenzi** [comment]
@costateixeira is this still a problem?

**Comment by costateixeira** [comment]
Yes, still a problem. But is anyone using _gencontinuous? If this is there for a while and if _gencontinuous builds after 5 seconds even when files haven't changed, I don't think it adds much.  If this is an important feature we could find another way to rebuild upon changes (but is that also what people want, any change triggers a new build?)


Anyway, here's the logo from another IG:
```
Publishing Content Failed: Stream closed

Use -? to get command line help

Stack Dump (for debugging):
java.io.IOException: Stream closed
        at java.base/sun.nio.cs.StreamEncoder.ensureOpen(StreamEncoder.java:51)
        at java.base/sun.nio.cs.StreamEncoder.write(StreamEncoder.java:125)
        at java.base/sun.nio.cs.StreamEncoder.write(StreamEncoder.java:142)
        at java.base/java.io.OutputStreamWriter.write(OutputStreamWriter.java:223)
        at java.base/java.io.Writer.write(Writer.java:249)
        at org.hl7.fhir.utilities.TextStreamWriter.ln(TextStreamWriter.java:53)
        at org.hl7.fhir.r5.utils.formats.CSVWriter.dump(CSVWriter.java:338)
        at org.hl7.fhir.igtools.publisher.Publisher.generate(Publisher.java:6365)
        at org.hl7.fhir.igtools.publisher.Publisher.execute(Publisher.java:915)
        at org.hl7.fhir.igtools.publisher.Publisher.main(Publisher.java:10756)
```

**Comment by costateixeira** [comment]
One of the offending lines in the stack above:
![image](https://user-images.githubusercontent.com/16153168/212775598-8a490652-5f30-4bb7-b816-3138f5b31f73.png)

**Comment by lmckenzi** [comment]
@costateixeira will raise a question on Zulip as to whether anyone actually wants/needs genContinuous.  If no-one wants it, we'll just remove it.
