### ISSUE TITLE
Error expanding ISO country-code & state value sets

### ISSUE THREAD

**Issue by realizm** [HL7/fhir-ig-publisher#843]
_genonce with jurisdiction option

publish-setup.json
```
...
jurisdiction: urn:iso:std:iso:3166#KR "Korea, Republic of" # https://www.hl7.org/fhir/valueset-jurisdiction.html
...

```
Console Log
```
FHIR IG Publisher Version 1.5.13 (Git# cbf40c33fbd2). Built 2024-01-18T03:47:31.696Z (26 hours old) 
Detected Java version: 17.0.10 from C:\Program Files\Amazon Corretto\jdk17.0.10_7 on Windows 11/amd64 (64bit). 4026MB available

...

java.lang.Exception: Error expanding ISO country-code & state value sets
        at org.hl7.fhir.igtools.publisher.Publisher.setupCountries(Publisher.java:9292)
        at org.hl7.fhir.igtools.publisher.Publisher.translateCountryCode(Publisher.java:9241)
        at org.hl7.fhir.igtools.publisher.Publisher.populateResourceEntry(Publisher.java:9113)
        at org.hl7.fhir.igtools.publisher.Publisher.generateSummaryOutputs(Publisher.java:8728)
        at org.hl7.fhir.igtools.publisher.Publisher.generate(Publisher.java:7498)
        at org.hl7.fhir.igtools.publisher.Publisher.createIg(Publisher.java:1143)
        at org.hl7.fhir.igtools.publisher.Publisher.execute(Publisher.java:972)
        at org.hl7.fhir.igtools.publisher.Publisher.main(Publisher.java:12487)
```

**Comment by grahamegrieve** [comment]
Should be fixed
