### ISSUE TITLE
(First) publication fails on missing package-feed.xml

### ISSUE THREAD

**Issue by jkiddo** [HL7/fhir-ig-publisher#849]
A preflight check should be conducted by the publisher on the missing package-feed.xml instead of one of the very last steps.

```
Check for Files to delete
  ... 4 files
Copy to new IG to /Users/jkiddo/work/falcon-ig/temp/web-root/run-20240124/
Exception in thread "main" java.lang.Error: Error: Attempt to copy /Users/jkiddo/work/falcon-ig/website/package-feed.xml but it doesn't exist
    at org.hl7.fhir.igtools.web.WebSourceProvider.needFile(WebSourceProvider.java:91)
    at org.hl7.fhir.igtools.web.PublicationProcess.updateFeed(PublicationProcess.java:667)
    at org.hl7.fhir.igtools.web.PublicationProcess.doPublish(PublicationProcess.java:559)
```

**Comment by jkiddo** [comment]
I'd advocate that if it isnt there then the tool should create it itself.

**Comment by costateixeira** [comment]
that makes sense.
