### ISSUE TITLE
Crash on slicing a sliced element

### ISSUE THREAD

**Issue by LodewijkSioen** [HL7/fhir-ig-publisher#862]
See: https://chat.fhir.org/#narrow/stream/215610-shorthand/topic/Crash.20on.20restricting.20re-sliced.20element
Example repo: https://github.com/LodewijkSioen/Fhsing-Expedition/blob/main/input/fsh/Slicing.fsh

The IG publisher crashed with the following exeption:
```
java.lang.Exception: Error generating snapshot for C:\Projects\Zodiac-IG\experimental\test\fsh-generated\resources\StructureDefinition-my-parameters-Specific(my-parameters-Specific): Unable to generate snapshot for http://example.org/StructureDefinition/my-parameters-Specific in C:\Projects\Zodiac-IG\experimental\test\fsh-generated\resources\StructureDefinition-my-parameters-Specific because Index 0 out of bounds for length 0
        at org.hl7.fhir.igtools.publisher.Publisher.generateSnapshots(Publisher.java:6757)
        at org.hl7.fhir.igtools.publisher.Publisher.loadConformance(Publisher.java:5683)
        at org.hl7.fhir.igtools.publisher.Publisher.createIg(Publisher.java:1134)
        at org.hl7.fhir.igtools.publisher.Publisher.execute(Publisher.java:980)
        at org.hl7.fhir.igtools.publisher.Publisher.main(Publisher.java:12505)
Caused by: org.hl7.fhir.exceptions.FHIRException: Unable to generate snapshot for http://example.org/StructureDefinition/my-parameters-Specific in C:\Projects\Zodiac-IG\experimental\test\fsh-generated\resources\StructureDefinition-my-parameters-Specific because Index 0 out of bounds for length 0
        at org.hl7.fhir.igtools.publisher.Publisher.generateSnapshot(Publisher.java:6838)
        at org.hl7.fhir.igtools.publisher.Publisher.generateSnapshots(Publisher.java:6755)
        ... 4 more
Caused by: java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
        at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:100)
        at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:106)
        at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:302)
        at java.base/java.util.Objects.checkIndex(Objects.java:385)
        at java.base/java.util.ArrayList.get(ArrayList.java:427)
        at org.hl7.fhir.r5.conformance.profile.ProfilePathProcessor.processPathWithSlicedBaseDefault(ProfilePathProcessor.java:1066)
        at org.hl7.fhir.r5.conformance.profile.ProfilePathProcessor.processPathWithSlicedBase(ProfilePathProcessor.java:988)
        at org.hl7.fhir.r5.conformance.profile.ProfilePathProcessor.processPaths(ProfilePathProcessor.java:184)
        at org.hl7.fhir.r5.conformance.profile.ProfilePathProcessor.processPathWithSlicedBaseDefault(ProfilePathProcessor.java:1102)
        at org.hl7.fhir.r5.conformance.profile.ProfilePathProcessor.processPathWithSlicedBase(ProfilePathProcessor.java:988)
        at org.hl7.fhir.r5.conformance.profile.ProfilePathProcessor.processPaths(ProfilePathProcessor.java:184)
        at org.hl7.fhir.r5.conformance.profile.ProfilePathProcessor.processPaths(ProfilePathProcessor.java:154)
        at org.hl7.fhir.r5.conformance.profile.ProfileUtilities.generateSnapshot(ProfileUtilities.java:753)
        at org.hl7.fhir.igtools.publisher.Publisher.generateSnapshot(Publisher.java:6832)
```

**Comment by grahamegrieve** [comment]
Fixed next release

**Comment by LodewijkSioen** [comment]
Tested and the crash no longer happens. Thanks!
