### ISSUE TITLE
NullPointer exception on parsing FhirPath expression

### ISSUE THREAD

**Issue by jkiddo** [HL7/fhir-ig-publisher#863]
A nullpointerexception is thrown in the `CrossViewRenderer` when having SearchParameter's like the following defined in the IG:

```json
{
  "resourceType": "SearchParameter",
  "id": "PractitionerFullName",
  "url": "http://example.com/SearchParameter/PractitionerFullName",
  "description": "Full name of the Practitioner",
  "name": "practitioner-fullname",
  "status": "active",
  "code": "fullName",
  "base": [
    "Practitioner"
  ],
  "type": "string",
  "expression": "Practitioner.name[0].given.join(' ') + ' ' + Practitioner.name[0].family",
  "xpathUsage": "normal"
}
```
It seems like the index access is not handled that well. Changing index access `[0]`to `first()`fixes it though both expressions are semantically equal according to https://hl7.org/fhirpath/N1/#first-collection

Stacktrace as follows:

```java
java.lang.NullPointerException: Cannot invoke "String.equals(Object)" because the return value of "org.hl7.fhir.r5.fhirpath.ExpressionNode.getName()" is null
	at org.hl7.fhir.igtools.renderers.CrossViewRenderer.refersToExtension(CrossViewRenderer.java:1143)
	at org.hl7.fhir.igtools.renderers.CrossViewRenderer.refersToExtension(CrossViewRenderer.java:1148)
	at org.hl7.fhir.igtools.renderers.CrossViewRenderer.refersToExtension(CrossViewRenderer.java:1148)
	at org.hl7.fhir.igtools.renderers.CrossViewRenderer.buildSearchTableForExtension(CrossViewRenderer.java:1134)
	at org.hl7.fhir.igtools.publisher.Publisher.generateSummaryOutputs(Publisher.java:8530)
	at org.hl7.fhir.igtools.publisher.Publisher.generate(Publisher.java:7512)
	at org.hl7.fhir.igtools.publisher.Publisher.createIg(Publisher.java:1151)
	at org.hl7.fhir.igtools.publisher.Publisher.execute(Publisher.java:980)
	at org.hl7.fhir.igtools.publisher.Publisher.main(Publisher.java:12505)

```

**Comment by jkiddo** [comment]
@markiantorno / @grahamegrieve should this be closed by now?
