### ISSUE TITLE
IG Publisher fails at the very last step cause a file does not exist

### ISSUE THREAD

**Issue by jkiddo** [HL7/fhir-ig-publisher#894]
Especially when the publication-request.json contains `"first": true,` ... then the following bug is kinda annoying:

```
Exception in thread "main" java.lang.Error: Error: Attempt to copy /Users/jkiddo/work/thp-ig-website/package-feed.xml but it doesn't exist
	at org.hl7.fhir.igtools.web.WebSourceProvider.needFile(WebSourceProvider.java:95)
	at org.hl7.fhir.igtools.web.PublicationProcess.updateFeed(PublicationProcess.java:667)
	at org.hl7.fhir.igtools.web.PublicationProcess.doPublish(PublicationProcess.java:559)
	at org.hl7.fhir.igtools.web.PublicationProcess.publishInner2(PublicationProcess.java:393)
	at org.hl7.fhir.igtools.web.PublicationProcess.publishInner(PublicationProcess.java:231)
	at org.hl7.fhir.igtools.web.PublicationProcess.publish(PublicationProcess.java:123)
	at org.hl7.fhir.igtools.publisher.Publisher.main(Publisher.java:12297)
Sending usage stats failed: test.fhir.org:80 failed to respond
```

- it could just as well have created that file, correct?

**Comment by grahamegrieve** [comment]
no it can't create that file, the file has data in it that doesn't come from anywhere else in the system

**Comment by jkiddo** [comment]
Bummer
