### ISSUE TITLE
Exception generating Narrative: null

### ISSUE THREAD

**Issue by keithboone** [HL7/fhir-ig-publisher#90]
This shows up while publishing:

java.lang.NullPointerException
	at org.hl7.fhir.r5.utils.NarrativeGenerator.renderLeaf(NarrativeGenerator.java:1534)
	at org.hl7.fhir.r5.utils.NarrativeGenerator.generateByProfile(NarrativeGenerator.java:1290)
	at org.hl7.fhir.r5.utils.NarrativeGenerator.generateByProfile(NarrativeGenerator.java:1312)
	at org.hl7.fhir.r5.utils.NarrativeGenerator.generateByProfile(NarrativeGenerator.java:1312)
	at org.hl7.fhir.r5.utils.NarrativeGenerator.generate(NarrativeGenerator.java:1208)
	at org.hl7.fhir.r5.utils.NarrativeGenerator.generate(NarrativeGenerator.java:1191)
	at org.hl7.fhir.igtools.publisher.Publisher.generateNarratives(Publisher.java:944)
	at org.hl7.fhir.igtools.publisher.Publisher.loadConformance(Publisher.java:3486)
	at org.hl7.fhir.igtools.publisher.Publisher.createIg(Publisher.java:819)
	at org.hl7.fhir.igtools.publisher.Publisher.execute(Publisher.java:680)
	at org.hl7.fhir.igtools.publisher.Publisher.main(Publisher.java:7141)

Producing this in output:
population

code: New Diagnostic Tests Ordered/Received (Details : {http://hl7.org/fhir/us/saner/CodeSystem/PopulationSystem code 'totalOrdersIncrease' = 'New Diagnostic Tests Ordered/Received; {http://terminology.hl7.org/CodeSystem/measure-population code 'initial-population' = 'Initial Population)

count:

**Exception generating Narrative: null**

Because of this:
```
      <count>
        <extension
                   url="http://hl7.org/fhir/StructureDefinition/data-absent-reason">
          <valueCode value="unsupported"/>
        </extension>
      </count>
```

**Comment by lmckenzi** [comment]
@keithboone is this issue still a problem or can we close?

**Comment by lmckenzi** [comment]
Presume this is no longer an issue.  If it happens again, please raise a new issue (or bring it up on IG-Creation)
