### ISSUE TITLE
hl7.terminology.r4#6.0.0/package/NamingSystem-v3-loinc.json includes invalid  character "?" in "type"element of "uniqueId"

### ISSUE THREAD

**Issue by kazuhiko-ohe** [HL7/fhir-ig-publisher#926]
IG publisher now always fails by an following error:
Error loading /Users/kohe/.fhir/packages/hl7.terminology.r4#6.0.0/package/NamingSystem-v3-loinc.json: Unknown NamingSystemIdentifierType code '?'

The cause is that hl7.terminology.r4#6.0.0/package/NamingSystem-v3-loinc.json includes invalid  character "?" in "type"element of "uniqueId".
{
    "resourceType": "NamingSystem",
    "id": "v3-loinc",
　　：：：：
"uniqueId": [
        {
            "type": "oid",
            "value": "2.16.840.1.113883.6.1",
            "preferred": true
        },
        {
            "type": "uri",
            "value": "http://loinc.org",
            "preferred": true
        },
        {
            "type": "?",  <=======　ERROR
            "value": "http://loinc.org/rdf/",
            "preferred": false
        }
    ]
}

**Comment by nickgarrard** [comment]
Same issue

**Comment by alejosv** [comment]
Same issue and everything stopped.

**Comment by paolov** [comment]
Same issue!! it worked at least until yesterday around midnight Europe time, then from the morning it keeps failing. We ere on version 1.6.15, tried to upgrade to 1.6.18 but still failing

**Comment by grahamegrieve** [comment]
This is fixed by a new release

**Comment by alejosv** [comment]
Not at all, the process continue until end but keep generate the same error:
```
...
Processing Conformance Resources                                                                     (00:03.093 / 04:02.275, 294Mb)
Load Dependency Info                                                                                 (00:00.002 / 04:02.278, 294Mb)
Load Info                                                                                            (00:00.002 / 04:02.280, 294Mb)
Load Resources                                                                                       (00:00.001 / 04:02.282, 295Mb)
Load Paths                                                                                           (00:00.220 / 04:02.502, 368Mb)
Generating Snapshots                                                                                 (00:00.000 / 04:02.503, 368Mb)
Check R4 / R4B                                                                                       (00:00.001 / 04:02.505, 368Mb)
Assign Comparison Ids                                                                                (00:00.060 / 04:02.565, 378Mb)
Propagating status                                                                                   (00:00.000 / 04:02.566, 378Mb)
Generating Narratives                                                                                (00:00.000 / 04:02.566, 378Mb)
Validating Conformance Resources                                                                     (00:00.751 / 04:03.318, 317Mb)
org.hl7.fhir.exceptions.FHIRException: Error loading /home/ubuntu/.fhir/packages/hl7.terminology.r4#6.0.0/package/NamingSystem-v3-loinc.json: Unknown NamingSystemIdentifierType code '?'
	at org.hl7.fhir.r5.context.SimpleWorkerContext$PackageResourceLoader.loadResource(SimpleWorkerContext.java:126)
	at org.hl7.fhir.r5.context.CanonicalResourceManager$CanonicalResourceProxy.getResource(CanonicalResourceManager.java:98)
	at org.hl7.fhir.r5.context.CanonicalResourceManager$CachedCanonicalResource.getResource(CanonicalResourceManager.java:158)
	at org.hl7.fhir.r5.context.CanonicalResourceManager.getList(CanonicalResourceManager.java:693)
	at org.hl7.fhir.r5.context.BaseWorkerContext.fetchResourcesByType(BaseWorkerContext.java:2515)
	at org.hl7.fhir.igtools.publisher.ValidationServices.resolveURL(ValidationServices.java:306)
	at org.hl7.fhir.validation.instance.InstanceValidator.validateReference(InstanceValidator.java:3121)
	at org.hl7.fhir.validation.instance.InstanceValidator.checkPrimitive(InstanceValidator.java:2775)
	at org.hl7.fhir.validation.instance.InstanceValidator.checkChildByDefinition(InstanceValidator.java:6359)
	at org.hl7.fhir.validation.instance.InstanceValidator.checkChild(InstanceValidator.java:6187)
	at org.hl7.fhir.validation.instance.InstanceValidator.validateElement(InstanceValidator.java:6113)
	at org.hl7.fhir.validation.instance.InstanceValidator.checkChildByDefinition(InstanceValidator.java:6506)
	at org.hl7.fhir.validation.instance.InstanceValidator.checkChild(InstanceValidator.java:6187)
	at org.hl7.fhir.validation.instance.InstanceValidator.validateElement(InstanceValidator.java:6113)
	at org.hl7.fhir.validation.instance.InstanceValidator.checkChildByDefinition(InstanceValidator.java:6506)
	at org.hl7.fhir.validation.instance.InstanceValidator.checkChild(InstanceValidator.java:6187)
	at org.hl7.fhir.validation.instance.InstanceValidator.validateElement(InstanceValidator.java:6113)
	at org.hl7.fhir.validation.instance.InstanceValidator.startInner(InstanceValidator.java:5592)
	at org.hl7.fhir.validation.instance.InstanceValidator.start(InstanceValidator.java:5361)
	at org.hl7.fhir.validation.instance.InstanceValidator.validateResource(InstanceValidator.java:7193)
	at org.hl7.fhir.validation.instance.InstanceValidator.validate(InstanceValidator.java:998)
	at org.hl7.fhir.igtools.publisher.Publisher.validate(Publisher.java:7182)
	at org.hl7.fhir.igtools.publisher.Publisher.validate(Publisher.java:7495)
	at org.hl7.fhir.igtools.publisher.Publisher.validate(Publisher.java:5662)
	at org.hl7.fhir.igtools.publisher.Publisher.loadConformance(Publisher.java:5609)
	at org.hl7.fhir.igtools.publisher.Publisher.createIg(Publisher.java:1177)
	at org.hl7.fhir.igtools.publisher.Publisher.execute(Publisher.java:1016)
	at org.hl7.fhir.igtools.publisher.Publisher.main(Publisher.java:13019)
Caused by: java.lang.IllegalArgumentException: Unknown NamingSystemIdentifierType code '?'
	at org.hl7.fhir.r4.model.NamingSystem$NamingSystemIdentifierTypeEnumFactory.fromCode(NamingSystem.java:327)
	at org.hl7.fhir.r4.model.NamingSystem$NamingSystemIdentifierTypeEnumFactory.fromCode(NamingSystem.java:314)
	at org.hl7.fhir.r4.formats.JsonParser.parseEnumeration(JsonParser.java:104)
	at org.hl7.fhir.r4.formats.JsonParser.parseNamingSystemNamingSystemUniqueIdComponentProperties(JsonParser.java:21605)
	at org.hl7.fhir.r4.formats.JsonParser.parseNamingSystemNamingSystemUniqueIdComponent(JsonParser.java:21597)
	at org.hl7.fhir.r4.formats.JsonParser.parseNamingSystemProperties(JsonParser.java:21588)
	at org.hl7.fhir.r4.formats.JsonParser.parseNamingSystem(JsonParser.java:21522)
	at org.hl7.fhir.r4.formats.JsonParser.parseResource(JsonParser.java:31970)
	at org.hl7.fhir.r4.formats.JsonParserBase.parse(JsonParserBase.java:131)
	at org.hl7.fhir.convertors.loaders.loaderR5.R4ToR5Loader.loadResource(R4ToR5Loader.java:116)
	at org.hl7.fhir.r5.context.SimpleWorkerContext$PackageResourceLoader.loadResource(SimpleWorkerContext.java:118)
	... 27 more
Check profiles & code systems                                                                        (00:02.045 / 04:05.363, 337Mb)
Check realm rules                                                                                    (00:00.001 / 04:05.365, 337Mb)
Previous Version Comparison                                                                          (00:00.000 / 04:05.365, 337Mb)
Validating Resources                                                                                 (00:00.012 / 04:05.378, 339Mb)
Processing Provenance Records                                                                        (00:00.258 / 04:05.637, 339Mb)
Generating Outputs in /lxcshared/minsacr-ig4.git/output                                              (00:00.001 / 04:05.638, 339Mb)
Generate Native Outputs                                                                              (00:00.713 / 04:06.351, 350Mb)
Run Template                                                                                         (00:32.886 / 04:39.238, 371Mb)
...
```

**Comment by collinmesser** [comment]
I'm still getting this error with version 1.6.18 as well.

**Comment by grahamegrieve** [comment]
the error will keep appearing in the logs until a new version of THO is released.
