### ISSUE TITLE
acceptable file extension for Binary of ".feature"

### ISSUE THREAD

**Issue by JohnMoehrke** [HL7/fhir-ig-publisher#930]
Gherkin script files use the file extension `.feature`. The IG publisher will not load these files into Binary, 

Given sushi-config.yaml
```
resources:
  Binary/give-consent.feature:
    extension:
      - url: http://hl7.org/fhir/StructureDefinition/implementationguide-resource-format
        valueCode: "text/x-gherkin"
```

gives this error in the IG publisher
```
Stack Dump (for debugging):                                                                          (00:00.001 / 00:43.015, 505Mb)
java.lang.Exception: Unable to find the source file for Binary/give-consent.feature: not specified, so tried Binary-give-consent.feature.xml, give-consent.feature.Binary.xml, Binary-give-consent.feature.json, Binary/give-consent.feature.xml, Binary/give-consent.feature.json, give-consent.feature.xml, and give-consent.feature.json (and lowercase resource name variants) in dirs [C:\Users\johnm\git\ConsentWithSeg-testing\fsh-generated\resources, C:\Users\johnm\git\ConsentWithSeg-testing\fsh-generated\resources, C:\Users\johnm\git\ConsentWithSeg-testing\input\tests]
        at org.hl7.fhir.igtools.publisher.SimpleFetcher.fetch(SimpleFetcher.java:246)
        at org.hl7.fhir.igtools.publisher.Publisher.load(Publisher.java:4423)
        at org.hl7.fhir.igtools.publisher.Publisher.createIg(Publisher.java:1172)
        at org.hl7.fhir.igtools.publisher.Publisher.execute(Publisher.java:1016)
        at org.hl7.fhir.igtools.publisher.Publisher.main(Publisher.java:13007)

```

----------------------

Loading them using ig-loader

```
Instance: B-gerkin-script
InstanceOf: Binary
Title: "Binary Gerkin script"
Description: "Example of a binary Gerkin script using Binary."
* contentType = #text/x-gherkin
* data = "ig-loader-give-consent.feature"
```

but this results in a QA ERROR
> Unknown file type give-consent.feature

It seems that the IG publisher needs to be told that `.feature` is an okay extension.

**Comment by JohnMoehrke** [comment]
can be seen and reproduced in https://github.com/JohnMoehrke/ConsentWithSeg-testing

**Comment by JohnMoehrke** [comment]
note that DocumentReference implementation of ig-loader forbids the contentType from being populated, contrary to the documentation.
