### ISSUE TITLE
Publisher fails at "Sending usage stats" stage

### ISSUE THREAD

**Issue by samanvp** [HL7/fhir-ig-publisher#967]
Here is the relevant logs:

```
Generate Summaries                                                                                   (04:13.890 / 09:24.365, 3Gb)
Generating Summary Outputs                                                                           (00:00.001 / 09:24.367, 3Gb)
Table of contents has a section with more than 222 entries.  Collapsing will not work reliably
DB Cumulative Time invested: 00:00:03.392
Sending Usage Stats to Server                                                                        (00:40.333 / 10:04.700, 3Gb)
## Memory (MB): Use = 3843, Free = 252, Total = 4096, Max = 4096                                     (00:00.035 / 10:04.736, 3Gb)
Reclaiming memory...                                                                                 (00:00.004 / 10:04.740, 3Gb)
## Memory (MB): Use = 3658, Free = 437, Total = 4096, Max = 4096                                     (00:05.367 / 10:10.107, 3Gb)
Run jekyll: jekyll build --destination "/srv/jekyll/output" (in folder /srv/jekyll/temp/pages)       (00:00.001 / 10:10.109, 3Gb)
Troubleshooting Note: usual cases for Jekyll to fail are:                                            (00:00.000 / 10:10.110, 3Gb)
* A failure to produce a fragment that is already logged in the output above                         (00:00.000 / 10:10.110, 3Gb)
* A reference to a manually edited file that hasn't been provided                                    (00:00.000 / 10:10.111, 3Gb)
Jekyll: ruby 3.1.1p18 (2022-02-18 revision 53f5fc4236) [x86_64-linux-musl]                           (00:00.123 / 10:10.235, 3Gb)
Jekyll: Source: /srv/jekyll/temp/pages                                                               (00:00.634 / 10:10.870, 3Gb)
Jekyll: Generating...                                                                                (00:00.000 / 10:10.870, 3Gb)
Jekyll: done in 35.[576](...) seconds.                                                                      (00:35.607 / 10:46.490, 3Gb)
Checking Output HTML                                                                                 (00:26.454 / 11:12.932, 3Gb)
found ... files                                                                                     (00:00.096 / 11:13.029, 3Gb)
.....................Sending usage stats failed: Operation timed out (Connection timed out)
...................
.....................................Publishing Content Failed: Computed path does not start with first element: /srv/jekyll/output, ../data/full-ig_xxx.0.1.0.zip (03:11.336 / 14:24.365, 3Gb)
                                                                                                     (00:00.001 / 14:24.367, 3Gb)
Use -? to get command line help                                                                      (00:00.002 / 14:24.369, 3Gb)
                                                                                                     (00:00.000 / 14:24.370, 3Gb)
Stack Dump (for debugging):                                                                          (00:00.003 / 14:24.373, 3Gb)
java.lang.RuntimeException: Computed path does not start with first element: /srv/jekyll/output, ../data/full-ig_xxx.0.1.0.zip
	at org.hl7.fhir.utilities.PathBuilder.checkPathIsChildOfTarget(PathBuilder.java:147)
	at org.hl7.fhir.utilities.PathBuilder.buildPath(PathBuilder.java:133)
	at org.hl7.fhir.igtools.publisher.HTMLInspector.checkTarget(HTMLInspector.java:911)
	at org.hl7.fhir.igtools.publisher.HTMLInspector.checkResolveLink(HTMLInspector.java:755)
	at org.hl7.fhir.igtools.publisher.HTMLInspector.checkLinks(HTMLInspector.java:659)
	at org.hl7.fhir.igtools.publisher.HTMLInspector.checkLinks(HTMLInspector.java:680)
	at org.hl7.fhir.igtools.publisher.HTMLInspector.checkLinks(HTMLInspector.java:680)
	at org.hl7.fhir.igtools.publisher.HTMLInspector.checkLinks(HTMLInspector.java:680)
	at org.hl7.fhir.igtools.publisher.HTMLInspector.checkLinks(HTMLInspector.java:680)
	at org.hl7.fhir.igtools.publisher.HTMLInspector.checkLinks(HTMLInspector.java:680)
	at org.hl7.fhir.igtools.publisher.HTMLInspector.checkLinks(HTMLInspector.java:680)
	at org.hl7.fhir.igtools.publisher.HTMLInspector.checkLinks(HTMLInspector.java:680)
	at org.hl7.fhir.igtools.publisher.HTMLInspector.checkLinks(HTMLInspector.java:680)
	at org.hl7.fhir.igtools.publisher.HTMLInspector.checkLinks(HTMLInspector.java:680)
	at org.hl7.fhir.igtools.publisher.HTMLInspector.checkLinks(HTMLInspector.java:680)
	at org.hl7.fhir.igtools.publisher.HTMLInspector.check(HTMLInspector.java:324)
	at org.hl7.fhir.igtools.publisher.Publisher.generate(Publisher.java:7771)
	at org.hl7.fhir.igtools.publisher.Publisher.createIg(Publisher.java:1223)
	at org.hl7.fhir.igtools.publisher.Publisher.execute(Publisher.java:1045)
	at org.hl7.fhir.igtools.publisher.Publisher.main(Publisher.java:13302)
```

Is there a way to disable sending usage stats to avoid this issue?

**Comment by lmckenzi** [comment]
This is not related to sending stats.  This is part of the link-checking process.  There's some sort of edge case in your HTML that is causing a failure.  Are you able to share a link to the IG (or branch of the IG) that causes this issue @samanvp?

**Comment by samanvp** [comment]
Thanks @lmckenzi for your reply.
This was indeed caused by some `md` files under `input/pagecontent/` and removing them fixed the issue.

> Is there a way to disable sending usage stats

I am still trying to figure this out, I looked for input flags to turn off this feature but I was not able to find anything. Can you please let me know if it's possible to turn off this feature?

**Comment by lmckenzi** [comment]
The usage stats has nothing to do with your issue.  It happens on a separate thread, so the message shows up wherever it shows up but it's almost never a source of a build issue.
